import { useRef, useState, useEffect, useCallback } from 'react';
import { createRoot } from 'react-dom/client';
import HighlightOverlay from '../modes/overlay/overlays/HighlightOverlay';
import PlayerDetectionOverlay from '../modes/overlay/overlays/PlayerDetectionOverlay';
import useHighlightRegions from '../modes/overlay/hooks/useHighlightRegions';
import { useVideo } from '../hooks/useVideo';
import '../index.css';

/**
 * Bug 38 — DEV-ONLY real-browser harness mounting the REAL modules under test:
 *
 *   Glitch 2 (auto-select): the REAL `useHighlightRegions` hook restores a region
 *     with keyframes:[] + detections (exactly the live primary path — the backend
 *     returns regions with no keyframes and a projected detection slice). The
 *     spotlight the REAL HighlightOverlay renders is `getHighlightAtTime`. The main
 *     player is placed OFF the geometric frame center with a higher-confidence
 *     bystander in the corner, so the spec can prove the auto spotlight chose the
 *     centered player, not the frame center and not the loud bystander.
 *
 *   Glitch 3 (paused frame-step): the REAL `useVideo` hook drives a real <video>
 *     (its handlers wired), and the step buttons call the REAL
 *     `stepForward`/`stepBackward` — so seek()'s paused requestVideoFrameCallback
 *     repaint path runs against a genuine media element.
 *
 * The 640x360 sample MP4 is generated by the spec's beforeAll (not committed).
 * bug38diag.html is not a vite build input, so none of this ships.
 */

const VW = 640;
const VH = 360;
const VIDEO_METADATA = { width: VW, height: VH, duration: 3, framerate: 30 };
const ZOOM = 1;
const PAN_OFFSET = { x: 0, y: 0 };
const SAMPLE = '/bug38diag-sample.mp4';

// Frame center is (320, 180). Main player is near-center but distinct; the
// bystander is a loud (high-confidence), equally-sized box in the corner.
export const MAIN_BOX = { x: 400, y: 150, width: 120, height: 200, confidence: 0.45 };
const BYSTANDER_BOX = { x: 70, y: 60, width: 120, height: 200, confidence: 0.98 };
const VIDEO_DETECTIONS = {
  videoWidth: VW,
  videoHeight: VH,
  fps: 30,
  detections: [
    { timestamp: 0.0, frame: 0, boxes: [BYSTANDER_BOX, MAIN_BOX] },
    { timestamp: 1.0, frame: 30, boxes: [BYSTANDER_BOX, MAIN_BOX] },
  ],
};

// ---- Glitch 2 section: real useHighlightRegions + real HighlightOverlay ----
function AutoSelectSection() {
  const videoRef = useRef(null);
  const regions = useHighlightRegions(VIDEO_METADATA);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    // restoreRegions takes duration as an ARG (no stale-state closure) and seeds
    // keyframes synchronously from `saved.detections` -- exactly the live primary
    // path (backend returns regions with keyframes:[] + detections). Our fix seeds
    // the start/end keyframes on the MAIN CENTERED player.
    regions.restoreRegions([
      {
        id: 'r1',
        start_time: 0.0,
        end_time: 2.0,
        keyframes: [],
        detections: VIDEO_DETECTIONS.detections,
        videoWidth: VW,
        videoHeight: VH,
        fps: 30,
      },
    ], 3);
    setReady(true);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // The auto/pre-selected spotlight at region start.
  const highlight = ready ? regions.getHighlightAtTime(0.2) : null;
  // Detection boxes to render for visual evidence.
  const boxes = ready ? VIDEO_DETECTIONS.detections[0].boxes : [];

  return (
    <div style={{ margin: 16, maxWidth: '100%' }}>
      <h3 data-testid="section-autoselect">Glitch 2: auto-select main centered player</h3>
      <div
        className="video-container"
        data-testid="autoselect-container"
        style={{ position: 'relative', width: 'min(100%, 640px)', height: VH, background: '#000' }}
      >
        <video ref={videoRef} src={SAMPLE} muted playsInline preload="auto"
          style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }} />
        {ready && (
          <PlayerDetectionOverlay
            videoRef={videoRef}
            videoMetadata={VIDEO_METADATA}
            detections={boxes}
            detectionVideoWidth={VW}
            detectionVideoHeight={VH}
            isEnabled
            onPlayerSelect={() => {}}
            zoom={ZOOM}
            panOffset={PAN_OFFSET}
          />
        )}
        {highlight && (
          <HighlightOverlay
            videoRef={videoRef}
            videoMetadata={VIDEO_METADATA}
            currentHighlight={highlight}
            onHighlightChange={() => {}}
            onHighlightComplete={() => {}}
            isEnabled
            editable
            zoom={ZOOM}
            panOffset={PAN_OFFSET}
          />
        )}
      </div>
      <pre data-testid="autoselect-json" style={{ fontSize: 12 }}>
        {highlight ? JSON.stringify({ x: highlight.x, y: highlight.y, radiusX: highlight.radiusX }) : 'loading'}
      </pre>
    </div>
  );
}

// ---- Glitch 3 section: real useVideo paused frame-step ----
function FrameStepSection() {
  const video = useVideo();
  const { videoRef, handlers, stepForward, stepBackward, pause, currentTime, isSeeking } = video;

  const doPause = useCallback(() => { if (videoRef.current) videoRef.current.pause(); pause(); }, [videoRef, pause]);

  return (
    <div style={{ margin: 16, maxWidth: '100%' }}>
      <h3 data-testid="section-framestep">Glitch 3: paused frame-by-frame step</h3>
      <div className="video-container" style={{ position: 'relative', width: 'min(100%, 640px)', height: VH, background: '#000' }}>
        <video
          ref={videoRef}
          src={SAMPLE}
          muted
          playsInline
          preload="auto"
          crossOrigin="anonymous"
          style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }}
          {...handlers}
        />
      </div>
      <div style={{ marginTop: 8, display: 'flex', gap: 8 }}>
        <button data-testid="pause" onClick={doPause} style={btn}>Pause</button>
        <button data-testid="step-back" onClick={stepBackward} style={btn}>◀ Frame</button>
        <button data-testid="step-fwd" onClick={stepForward} style={btn}>Frame ▶</button>
      </div>
      <span data-testid="framestep-status" style={{ fontSize: 12 }}>
        {`t=${(currentTime || 0).toFixed(3)} seeking=${isSeeking}`}
      </span>
    </div>
  );
}

const btn = { padding: '8px 12px', background: '#374151', color: '#fff', borderRadius: 6, border: 0 };

function Harness() {
  // overflowX hidden so the fixed-size diag stage (a synthetic harness, not the
  // real responsive app) never reports document-level horizontal overflow during
  // the QA responsiveSweep at 375px.
  return (
    <div style={{ overflowX: 'hidden', maxWidth: '100vw' }}>
      <AutoSelectSection />
      <FrameStepSection />
    </div>
  );
}

createRoot(document.getElementById('bug38diag-root')).render(<Harness />);
