import { useRef, useState, useCallback, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
// eslint-disable-next-line no-unused-vars -- rendered as JSX below; repo eslint lacks react/jsx-uses-vars
import HighlightOverlay from '../modes/overlay/overlays/HighlightOverlay';
import { OverlayContainer } from '../containers/OverlayContainer';
import '../index.css'; // Tailwind — the move grip's rounded-full/flex classes need it

/**
 * T5450 — DEV-ONLY real-browser harness for the overlay spotlight circle + loop button.
 *
 * Mounts the REAL HighlightOverlay and the REAL OverlayContainer hook so the
 * behaviours under test run genuine code, not a re-implementation:
 *   - `showPlayerBoxes` / `togglePlayerBoxes` come from OverlayContainer → the circle's
 *     `editable = !showPlayerBoxes` gate is the real one.
 *   - `handlePlaySpotlight` (the play/pause-toggle fix) and `useSpotlightLoop` (loop wrap)
 *     run inside OverlayContainer against a REAL <video> element, so `video.paused` /
 *     `video.currentTime` are real.
 *   - The video-container tap-nav gate mirrors OverlayModeView (yields while editable).
 *
 * A real 640x360 sample MP4 is served at /overlaydiag-sample.mp4 (generated by the
 * Playwright spec's beforeAll via ffmpeg; not committed). NOT shipped: overlaydiag.html
 * is not a vite build input, so this never enters the production bundle.
 */

const VIDEO_METADATA = { width: 640, height: 360, duration: 3, framerate: 30 };
const ZOOM = 1;
const PAN_OFFSET = { x: 0, y: 0 };
// Spotlight span well inside the 3s clip so the loop can wrap quickly.
const SPAN = { start: 0.4, end: 1.2 };
const REGION = { id: 'r1', startTime: SPAN.start, endTime: SPAN.end, enabled: true, detections: [] };
const INITIAL_HIGHLIGHT = {
  x: 320, y: 180, radiusX: 50, radiusY: 80,
  strokeOpacity: 0.85, fillOpacity: 0.05, color: '#FFD400',
};

// eslint-disable-next-line no-unused-vars -- rendered as JSX at the bottom; repo eslint lacks react/jsx-uses-vars
function OverlayDiagHarness() {
  const videoRef = useRef(null);
  const [highlight, setHighlight] = useState(INITIAL_HIGHLIGHT);
  // Real video playback state, tracked off the <video> element's own events.
  const [currentTime, setCurrentTime] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isSeeking, setIsSeeking] = useState(false);

  useEffect(() => {
    const v = videoRef.current;
    if (!v) return;
    const onTime = () => setCurrentTime(v.currentTime);
    const onPlay = () => setIsPlaying(true);
    const onPause = () => setIsPlaying(false);
    const onSeeking = () => setIsSeeking(true);
    const onSeeked = () => setIsSeeking(false);
    v.addEventListener('timeupdate', onTime);
    v.addEventListener('play', onPlay);
    v.addEventListener('pause', onPause);
    v.addEventListener('seeking', onSeeking);
    v.addEventListener('seeked', onSeeked);
    return () => {
      v.removeEventListener('timeupdate', onTime);
      v.removeEventListener('play', onPlay);
      v.removeEventListener('pause', onPause);
      v.removeEventListener('seeking', onSeeking);
      v.removeEventListener('seeked', onSeeked);
    };
  }, []);

  const seek = useCallback((t) => { if (videoRef.current) videoRef.current.currentTime = t; }, []);
  const togglePlay = useCallback(() => {
    const v = videoRef.current;
    if (!v) return;
    if (v.paused) v.play().catch(() => {}); else v.pause();
  }, []);

  // The REAL OverlayContainer hook. Only the props the spotlight/toggle paths touch are
  // wired live; the rest are inert stubs (handlers are never fired in this harness).
  const overlay = OverlayContainer({
    videoRef, currentTime, duration: VIDEO_METADATA.duration, isPlaying, isSeeking, seek, togglePlay,
    framingVideoUrl: null, framingMetadata: null,
    keyframes: [], segments: null, segmentSpeeds: {}, segmentBoundaries: [], trimRange: null,
    selectedProjectId: 'diag', selectedProject: null,
    clips: [], hasClips: false,
    editorMode: 'overlay', setEditorMode: () => {}, setSelectedLayer: () => {},
    overlayVideoFile: null, overlayVideoUrl: '/overlaydiag-sample.mp4', overlayVideoMetadata: VIDEO_METADATA,
    overlayClipMetadata: null, isLoadingWorkingVideo: false,
    setOverlayVideoFile: () => {}, setOverlayVideoUrl: () => {}, setOverlayVideoMetadata: () => {},
    setOverlayClipMetadata: () => {}, setIsLoadingWorkingVideo: () => {},
    dragHighlight: null, setDragHighlight: () => {},
    selectedHighlightKeyframeTime: null, setSelectedHighlightKeyframeTime: () => {},
    highlightEffectType: 'dark_overlay', setHighlightEffectType: () => {}, highlightColor: null,
    overlaySyncState: 'ready', overlayLoadedProjectId: 'diag',
    highlightRegions: [REGION], highlightBoundaries: [], highlightRegionKeyframes: [], highlightRegionsFramerate: 30,
    initializeHighlightRegions: () => {}, resetHighlightRegions: () => {},
    addHighlightRegion: () => {}, deleteHighlightRegion: () => {},
    moveHighlightRegionStart: () => {}, moveHighlightRegionEnd: () => {},
    toggleHighlightRegion: () => {}, addHighlightRegionKeyframe: () => {}, removeHighlightRegionKeyframe: () => {},
    getRegionAtTime: () => REGION, isTimeInEnabledRegion: () => false, getRegionHighlightAtTime: () => null,
    getRegionsForExport: () => [], restoreHighlightRegions: () => {}, initializeHighlightRegionsFromClips: () => {},
  });

  const { showPlayerBoxes, togglePlayerBoxes, handlePlaySpotlight, spotlightPlayMode, isPastSpotlight } = overlay;
  const editable = !showPlayerBoxes;

  const onHighlightChange = useCallback((h) => setHighlight(h), []);
  const onHighlightComplete = useCallback((h) => setHighlight(h), []);

  return (
    <div style={{ margin: 40, width: 640 }}>
      <div style={{ marginBottom: 12, display: 'flex', gap: 12, alignItems: 'center' }}>
        <button
          data-testid="toggle-player-boxes"
          onClick={togglePlayerBoxes}
          style={{ padding: '8px 12px', background: '#374151', color: '#fff', borderRadius: 6 }}
        >
          {showPlayerBoxes ? 'Player boxes: ON (display-only)' : 'Player boxes: OFF (editable)'}
        </button>
        <button
          data-testid="play-spotlight"
          onClick={handlePlaySpotlight}
          style={{ padding: '8px 12px', background: '#7c3aed', color: '#fff', borderRadius: 6 }}
        >
          Play spotlight
        </button>
        <span data-testid="status" style={{ color: '#d1d5db', fontSize: 12 }}>
          {`t=${currentTime.toFixed(2)} playing=${isPlaying} mode=${spotlightPlayMode} past=${isPastSpotlight}`}
        </span>
      </div>

      {/* Video container. The tap-nav gate mirrors OverlayModeView: it YIELDS while
          editable so a circle drag is never stolen by play/pause. */}
      <div
        className="video-container"
        data-testid="video-container"
        style={{ position: 'relative', width: 640, height: 360, background: '#000' }}
        onClick={editable ? undefined : togglePlay}
      >
        <video
          ref={videoRef}
          src="/overlaydiag-sample.mp4"
          muted
          playsInline
          preload="auto"
          style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }}
        />
        <HighlightOverlay
          videoRef={videoRef}
          videoMetadata={VIDEO_METADATA}
          currentHighlight={highlight}
          onHighlightChange={onHighlightChange}
          onHighlightComplete={onHighlightComplete}
          isEnabled
          zoom={ZOOM}
          panOffset={PAN_OFFSET}
          editable={editable}
        />
      </div>
    </div>
  );
}

createRoot(document.getElementById('overlaydiag-root')).render(<OverlayDiagHarness />);
