import { useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import PlayerDetectionOverlay from '../modes/overlay/overlays/PlayerDetectionOverlay';
import OverrideHint from '../modes/overlay/overlays/OverrideHint';
import '../index.css'; // Tailwind — the hint pill + badge classes need it

/**
 * T5643 — DEV-ONLY real-browser harness proving the moved + gated override hint.
 *
 * Mounts the REAL PlayerDetectionOverlay (source of the "N players detected" badge,
 * `top-4 right-4` inside `.video-container`) and the REAL OverrideHint, nested EXACTLY
 * like OverlayModeView.jsx does in production:
 *
 *   <div class="relative">                 outer wrapper (OverlayModeView.jsx ~L437)
 *     <div class="video-player-container relative">   VideoPlayer.jsx root
 *       <div class="video-container relative">        VideoPlayer.jsx inner
 *         <video/>
 *         <PlayerDetectionOverlay/>        -> renders the "N players detected" badge
 *       </div>
 *     </div>
 *     <OverrideHint/>                      sibling of video-player-container, same as
 *                                           OverlayModeView.jsx ~L530-537
 *   </div>
 *
 * None of these three containers has padding/margin between them, so they share the
 * same top-left origin — proving the hint's `top-14 right-4` sits directly under the
 * badge's `top-4 right-4` here proves it in production too.
 *
 * Also mirrors OverlayModeView's T5643 gate formula so the "hides while a tracking
 * keyframe is selected" acceptance criterion is provable without the full app/backend:
 *   showOverrideHint = hasVisibleSpotlight && showPlayerBoxes && !overrideUsed
 *                       && selectedHighlightKeyframeIndex === null
 *
 * A real 640x360 sample MP4 is served at /overlaydiag-sample.mp4 (generated by the
 * Playwright spec's beforeAll via ffmpeg; not committed). overlaydiag-t5643.html is not
 * a vite build input, so this never enters the production bundle.
 */

const VIDEO_METADATA = { width: 640, height: 360, duration: 3, framerate: 30 };
const ZOOM = 1; // stable reference — see T5610 landmine in keyframes-framing.md
const PAN_OFFSET = { x: 0, y: 0 };

// 8 fake detections -> "8 players detected", matching the task doc's own example.
const DETECTIONS = Array.from({ length: 8 }, (_, i) => ({
  x: 60 + (i % 4) * 140,
  y: 90 + Math.floor(i / 4) * 160,
  width: 40,
  height: 90,
  confidence: 0.9,
}));

function OverrideHintPlacementHarness() {
  const videoRef = useRef(null);
  const [showPlayerBoxes, setShowPlayerBoxes] = useState(true); // tracking ON by default
  const [overrideUsed, setOverrideUsed] = useState(false);
  const [selectedHighlightKeyframeIndex, setSelectedHighlightKeyframeIndex] = useState(null);

  // ---- OverlayModeView T5643 glue (mirrored) ----
  const hasVisibleSpotlight = true; // region is always active in this harness
  const showOverrideHint = hasVisibleSpotlight && showPlayerBoxes && !overrideUsed
    && selectedHighlightKeyframeIndex === null;
  const overrideHintText = 'Tap the spotlight to adjust it — or hide tracking to edit freely';

  return (
    <div style={{ margin: '20px auto', width: '100%', maxWidth: 640, boxSizing: 'border-box', padding: '0 8px' }}>
      <div style={{ marginBottom: 12, display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap' }}>
        <button
          data-testid="toggle-player-boxes"
          onClick={() => setShowPlayerBoxes((v) => !v)}
          style={{ padding: '8px 12px', background: '#374151', color: '#fff', borderRadius: 6 }}
        >
          {showPlayerBoxes ? 'Tracking: ON' : 'Tracking: OFF'}
        </button>
        <button
          data-testid="toggle-frame-selected"
          onClick={() => setSelectedHighlightKeyframeIndex((v) => (v === null ? 0 : null))}
          style={{ padding: '8px 12px', background: '#374151', color: '#fff', borderRadius: 6 }}
        >
          {selectedHighlightKeyframeIndex === null ? 'Frame: not selected' : 'Frame: selected'}
        </button>
        <button
          data-testid="mark-override-used"
          onClick={() => setOverrideUsed(true)}
          style={{ padding: '8px 12px', background: '#374151', color: '#fff', borderRadius: 6 }}
        >
          Mark override used
        </button>
        <span data-testid="status" style={{ color: '#d1d5db', fontSize: 12 }}>
          {`showPlayerBoxes=${showPlayerBoxes} selectedFrame=${selectedHighlightKeyframeIndex} overrideUsed=${overrideUsed} showHint=${showOverrideHint}`}
        </span>
      </div>

      {/* Mirrors OverlayModeView.jsx ~L437: outer relative wrapper. */}
      <div className="relative bg-gray-900" style={{ width: '100%', maxWidth: 640 }}>
        {/* Mirrors VideoPlayer.jsx root ("video-player-container"). */}
        <div className="video-player-container rounded-t-lg overflow-hidden relative outline-none">
          {/* Mirrors VideoPlayer.jsx inner ("video-container"). */}
          <div
            className="relative video-container overflow-hidden"
            data-testid="video-container"
            style={{ width: '100%', aspectRatio: '640 / 360', background: '#000' }}
          >
            <video
              ref={videoRef}
              src="/overlaydiag-sample.mp4"
              muted
              playsInline
              preload="auto"
              style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }}
            />
            <PlayerDetectionOverlay
              videoRef={videoRef}
              videoMetadata={VIDEO_METADATA}
              detections={DETECTIONS}
              detectionVideoWidth={640}
              detectionVideoHeight={360}
              zoom={ZOOM}
              panOffset={PAN_OFFSET}
              isDisabled={!showPlayerBoxes}
            />
          </div>
        </div>

        {/* Mirrors OverlayModeView.jsx ~L530-537: OverrideHint as a sibling of the
            video player, in the SAME outer relative wrapper as the badge above. */}
        <OverrideHint visible={showOverrideHint} text={overrideHintText} />
      </div>
    </div>
  );
}

createRoot(document.getElementById('overlaydiag-t5643-root')).render(<OverrideHintPlacementHarness />);
