import { createRoot } from 'react-dom/client';
import { IntroStoryPlayer } from '../components/introcards/IntroStoryPlayer';
import '../index.css'; // Tailwind — the fixed/inset/z classes need it

/**
 * T10680 — DEV-ONLY real-browser harness for the IntroStoryPlayer-mounted player
 * (the shape PublishedReelsPanel / DownloadsPanel use). intro=null so it starts
 * directly in the reels region and mounts the REAL CollectionPlayer with
 * transport ON, plus IntroStoryPlayer's own composite scrubber (a SIBLING of the
 * panel, in a separate fixed z-90 container).
 *
 * The point this harness proves that jsdom cannot: entering fullscreen (CSS
 * expand, and native where the browser allows it) must NOT drop the composite
 * scrubber, because CollectionPlayer requests fullscreen on the wrapper that
 * encloses both the panel and the scrubber (`fullscreenTarget`).
 *
 * Sample is a VP9 WebM generated by the spec's beforeAll and served at
 * /introstoryplayerdiag-sample.webm (not committed). WebM (not the T5860 mp4)
 * because headless Chromium ships VP9 but not H.264 — this harness needs the
 * video to ACTUALLY play so the isPlaying edge (glyph fade) is exercised for
 * real. Not in the prod bundle: Vite's build input is index.html only; this
 * html entry is never added to rollupOptions.input.
 */

const SAMPLE = '/introstoryplayerdiag-sample.webm';
const REELS = [
  { id: 1, name: 'Diag Reel A', streamUrl: SAMPLE, aspect_ratio: '9:16', duration: 3 },
  { id: 2, name: 'Diag Reel B', streamUrl: SAMPLE, aspect_ratio: '9:16', duration: 3 },
];

function Harness() {
  return (
    <div style={{ minHeight: '100dvh', background: '#111827' }}>
      <IntroStoryPlayer intro={null} aspect="9:16" reels={REELS} title="Diag Collection" onClose={() => {}} />
    </div>
  );
}

createRoot(document.getElementById('root')).render(<Harness />);
