import { test, expect } from '@playwright/test';
import { execSync } from 'node:child_process';
import { existsSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * T5450 — REAL BROWSER (chromium) proof for the overlay spotlight circle + loop button,
 * driven through a dev-only harness (/overlaydiag.html) that mounts the REAL
 * HighlightOverlay + the REAL OverlayContainer hook against a REAL <video>.
 *
 * Proven here (jsdom is insufficient — T5390's first attempt passed jsdom, failed on
 * real touch), in BOTH a coarse (touch) and a fine (mouse) context:
 *   1. player boxes OFF -> resize handles + center move grip visible (no tap); ON -> none
 *   2. drag the center grip -> circle center moves; drag a rim handle -> resizes
 *   3. while editable, a drag over the circle does NOT change video.currentTime
 *   4. press primary while playing -> pauses; while paused -> plays; loop wraps at span end
 *   5. grip + handles measure >=44px on the coarse context
 *
 * Post-refactor HighlightOverlay has NO pointerType branch (unified pointer events), so a
 * mouse-driven drag exercises the same code path in both contexts; the coarse context's
 * distinct value is real hit-testing + the >=44px CSS sizing (useIsCoarsePointer).
 *
 * The 640x360 sample MP4 is generated by ffmpeg in beforeAll (not committed).
 * Run: cd src/frontend && npx playwright test e2e/T5450-overlay-circle-and-loop.qa.spec.js
 */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SAMPLE = path.resolve(__dirname, '..', 'public', 'overlaydiag-sample.mp4');
const HARNESS = 'http://localhost:5173/overlaydiag.html';

const BODY = '[data-testid="highlight-body"]';
const GRIP = '[data-testid="highlight-move-grip"]';
const HANDLE_H = '[data-testid="highlight-handle-horizontal"]';
const HANDLE_V = '[data-testid="highlight-handle-vertical"]';
const TOGGLE = '[data-testid="toggle-player-boxes"]';
const PLAY = '[data-testid="play-spotlight"]';

test.beforeAll(() => {
  if (!existsSync(SAMPLE)) {
    execSync(
      `ffmpeg -y -f lavfi -i testsrc=duration=3:size=640x360:rate=30 -pix_fmt yuv420p -movflags +faststart "${SAMPLE}"`,
      { stdio: 'ignore' }
    );
  }
});

test.afterAll(() => {
  if (existsSync(SAMPLE)) unlinkSync(SAMPLE);
});

async function centerOf(locator) {
  const b = await locator.boundingBox();
  if (!b) throw new Error('element not visible');
  return { x: b.x + b.width / 2, y: b.y + b.height / 2, w: b.width, h: b.height };
}

/** Real-browser pointer drag by (dx,dy) from a locator's center. */
async function dragFrom(page, locator, dx, dy) {
  const c = await centerOf(locator);
  await page.mouse.move(c.x, c.y);
  await page.mouse.down();
  await page.mouse.move(c.x + dx, c.y + dy, { steps: 8 });
  await page.mouse.up();
  await page.waitForTimeout(60);
}

async function makeEditable(page) {
  // Default is player boxes ON (display-only). One toggle -> editable.
  await page.locator(TOGGLE).click();
  await expect(page.locator(GRIP)).toBeVisible();
}

function suite(label, contextOpts) {
  test.describe(`T5450 overlay circle + loop — ${label}`, () => {
    test.use(contextOpts);

    test('1) levers gated on player-tracking layer (OFF shows handles + grip, ON hides)', async ({ page }) => {
      await page.goto(HARNESS);
      await expect(page.locator(BODY)).toBeVisible();
      // Player boxes ON (default) -> display only.
      await expect(page.locator(GRIP)).toHaveCount(0);
      await expect(page.locator(HANDLE_H)).toHaveCount(0);
      // Toggle OFF -> editable levers appear with no tap-to-select.
      await page.locator(TOGGLE).click();
      await expect(page.locator(GRIP)).toBeVisible();
      await expect(page.locator(HANDLE_H)).toBeVisible();
      await expect(page.locator(HANDLE_V)).toBeVisible();
      // Toggle back ON -> display only again.
      await page.locator(TOGGLE).click();
      await expect(page.locator(GRIP)).toHaveCount(0);
      await expect(page.locator(HANDLE_H)).toHaveCount(0);
    });

    test('2) center grip MOVES the circle; rim handle RESIZES it', async ({ page }) => {
      await page.goto(HARNESS);
      await makeEditable(page);

      const before = await centerOf(page.locator(BODY));
      await dragFrom(page, page.locator(GRIP), 60, 40);
      const afterMove = await centerOf(page.locator(BODY));
      expect(Math.round(afterMove.x - before.x), 'grip drag moved center x').toBeGreaterThan(30);
      expect(Math.round(afterMove.y - before.y), 'grip drag moved center y').toBeGreaterThan(20);

      // Resize via the horizontal rim handle (widens the ellipse).
      const wBefore = (await page.locator(BODY).boundingBox()).width;
      await dragFrom(page, page.locator(HANDLE_H), 40, 0);
      const wAfter = (await page.locator(BODY).boundingBox()).width;
      expect(Math.round(wAfter - wBefore), 'handle drag widened the circle').toBeGreaterThan(20);
    });

    test('3) while editable, a drag over the circle does NOT scrub the video', async ({ page }) => {
      await page.goto(HARNESS);
      await makeEditable(page);
      const t0 = await page.evaluate(() => document.querySelector('video').currentTime);
      const paused0 = await page.evaluate(() => document.querySelector('video').paused);
      await dragFrom(page, page.locator(BODY), 50, 30);
      const t1 = await page.evaluate(() => document.querySelector('video').currentTime);
      const paused1 = await page.evaluate(() => document.querySelector('video').paused);
      expect(t1, 'currentTime unchanged during circle drag').toBeCloseTo(t0, 3);
      expect(paused1, 'still paused (tap-nav yielded)').toBe(paused0);
    });

    test('5) grip + handles are >=44px on coarse pointers', async ({ page }) => {
      await page.goto(HARNESS);
      await makeEditable(page);
      const grip = await page.locator(GRIP).boundingBox();
      const hHit = await page.locator(HANDLE_H).boundingBox();
      const vHit = await page.locator(HANDLE_V).boundingBox();
      if (label === 'coarse (touch)') {
        expect(grip.width, 'grip width').toBeGreaterThanOrEqual(44);
        expect(grip.height, 'grip height').toBeGreaterThanOrEqual(44);
        expect(hHit.width, 'h-handle hit width').toBeGreaterThanOrEqual(44);
        expect(vHit.height, 'v-handle hit height').toBeGreaterThanOrEqual(44);
      } else {
        // Fine pointer keeps the compact desktop sizing.
        expect(grip.width).toBeLessThan(44);
      }
    });
  });
}

suite('fine (mouse)', {});
suite('coarse (touch)', { hasTouch: true, isMobile: true, viewport: { width: 412, height: 915 } });

/**
 * 4) Loop button = TRUE play/pause toggle (the core bug fix). Runs once (fine context is
 * enough — the handler is device-agnostic). Also proves the loop wraps at span end.
 */
test.describe('T5450 loop button play/pause toggle', () => {
  test('press plays (seek to span start), press again pauses; loop wraps at span end', async ({ page }) => {
    await page.goto(HARNESS);
    // Paused, currentTime 0 (outside span [0.4,1.2]). Press primary -> loop + seek + play.
    await page.locator(PLAY).click();
    await page.waitForFunction(() => !document.querySelector('video').paused, null, { timeout: 4000 });
    const tStart = await page.evaluate(() => document.querySelector('video').currentTime);
    expect(tStart, 'seeked to span start (~0.4) on play').toBeGreaterThanOrEqual(0.35);
    expect(tStart, 'seeked to span start (~0.4) on play').toBeLessThan(0.9);

    // Let it play across the span end and observe the loop hold it inside the span.
    let maxSeen = 0;
    for (let i = 0; i < 16; i++) {
      await page.waitForTimeout(120);
      const t = await page.evaluate(() => document.querySelector('video').currentTime);
      maxSeen = Math.max(maxSeen, t);
    }
    // useSpotlightLoop wraps at end (~1.2). If the toggle/loop worked, playback never
    // runs away to the 3s clip end.
    expect(maxSeen, 'loop kept playback inside the span (< end + margin)').toBeLessThan(1.6);
    expect(maxSeen, 'video actually advanced past mid-span (it played)').toBeGreaterThan(0.7);

    // THE fix: pressing primary WHILE PLAYING pauses (old bug: it kept looping).
    await page.locator(PLAY).click();
    await page.waitForFunction(() => document.querySelector('video').paused, null, { timeout: 4000 });
    expect(await page.evaluate(() => document.querySelector('video').paused)).toBe(true);

    // Pressing again while paused resumes play.
    await page.locator(PLAY).click();
    await page.waitForFunction(() => !document.querySelector('video').paused, null, { timeout: 4000 });
    expect(await page.evaluate(() => document.querySelector('video').paused)).toBe(false);
  });
});
