import { test, expect } from '@playwright/test';
import { execSync } from 'node:child_process';
import { existsSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { skipOnDeployedTarget } from './helpers/targetEnv.js';

/**
 * T5450 — REAL BROWSER (chromium) proof for the overlay LOOP BUTTON, driven through a
 * dev-only harness (/overlaydiag.html) that mounts the REAL HighlightOverlay + the REAL
 * OverlayContainer hook against a REAL <video>.
 *
 * Covers T5450's criterion 4: press primary while playing -> pauses; while paused ->
 * plays; the loop wraps at span end (jsdom cannot prove this — it needs real playback).
 *
 * SCOPE NOTE — criteria 1/2/3/5 (grip/handle gating, move, no-scrub, >=44px) USED to live
 * here too, against `highlight-move-grip` + `highlight-handle-horizontal|vertical`. T5570
 * (2567e90e) then replaced that interaction model: there is no center grip on desktop
 * (drag the circle body), the touch grip became `highlight-move-lever` (coarse only), and
 * the rim handles became four `highlight-corner-{nw,ne,sw,se}` handles. T5610 re-proves
 * every one of those criteria against the CURRENT model, in the same two contexts, on the
 * same harness family:
 *   1/gating -> T5610 tests 1 + 4     2/move + 3/no-scrub -> T5610 test 2
 *   5/>=44px -> T5610 test 5          resize -> HighlightOverlay.override|touch.test.jsx
 * Those 8 tests here were therefore stale duplicates asserting a removed DOM contract
 * (they timed out for ~60s each), so they were removed rather than rewritten into a
 * second copy of T5610. The loop coverage below is unique to this spec and passes.
 *
 * The 640x360 sample MP4 is generated by ffmpeg in beforeAll (not committed).
 * Run: cd src/frontend && npx playwright test e2e/T5450-overlay-circle-and-loop.qa.spec.js
 */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SAMPLE = path.resolve(__dirname, '..', 'public', 'overlaydiag-sample.mp4');
const HARNESS = '/overlaydiag.html';

const PLAY = '[data-testid="play-spotlight"]';

test.beforeAll(() => {
  if (!existsSync(SAMPLE)) {
    execSync(
      `ffmpeg -y -f lavfi -i testsrc=duration=3:size=640x360:rate=30 -pix_fmt yuv420p -movflags +faststart "${SAMPLE}"`,
      { stdio: 'ignore' }
    );
  }
});

test.afterAll(() => {
  if (existsSync(SAMPLE)) unlinkSync(SAMPLE);
});

/**
 * 4) Loop button = TRUE play/pause toggle (the core bug fix). Runs once (fine context is
 * enough — the handler is device-agnostic). Also proves the loop wraps at span end.
 */
test.describe('T5450 loop button play/pause toggle', () => {
  // /overlaydiag.html is a Vite-dev-only harness page: not an input to the production
  // build, so on a deployed target this RELATIVE path resolves against the Pages origin
  // and the SPA catch-all serves index.html instead — the harness never mounts.
  skipOnDeployedTarget(test, 'drives the dev-only /overlaydiag.html harness page, which does not exist in a production BUILD');

  test('press plays (seek to span start), press again pauses; loop wraps at span end', async ({ page }) => {
    await page.goto(HARNESS);
    // Paused, currentTime 0 (outside span [0.4,1.2]). Press primary -> loop + seek + play.
    await page.locator(PLAY).click();
    await page.waitForFunction(() => !document.querySelector('video').paused, null, { timeout: 4000 });
    const tStart = await page.evaluate(() => document.querySelector('video').currentTime);
    expect(tStart, 'seeked to span start (~0.4) on play').toBeGreaterThanOrEqual(0.35);
    expect(tStart, 'seeked to span start (~0.4) on play').toBeLessThan(0.9);

    // Let it play across the span end and observe the loop hold it inside the span.
    let maxSeen = 0;
    for (let i = 0; i < 16; i++) {
      await page.waitForTimeout(120);
      const t = await page.evaluate(() => document.querySelector('video').currentTime);
      maxSeen = Math.max(maxSeen, t);
    }
    // useSpotlightLoop wraps at end (~1.2). If the toggle/loop worked, playback never
    // runs away to the 3s clip end.
    expect(maxSeen, 'loop kept playback inside the span (< end + margin)').toBeLessThan(1.6);
    expect(maxSeen, 'video actually advanced past mid-span (it played)').toBeGreaterThan(0.7);

    // THE fix: pressing primary WHILE PLAYING pauses (old bug: it kept looping).
    await page.locator(PLAY).click();
    await page.waitForFunction(() => document.querySelector('video').paused, null, { timeout: 4000 });
    expect(await page.evaluate(() => document.querySelector('video').paused)).toBe(true);

    // Pressing again while paused resumes play.
    await page.locator(PLAY).click();
    await page.waitForFunction(() => !document.querySelector('video').paused, null, { timeout: 4000 });
    expect(await page.evaluate(() => document.querySelector('video').paused)).toBe(false);
  });
});
