import { test, expect } from '@playwright/test';
import { execSync } from 'node:child_process';
import { existsSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { saveEvidence, responsiveSweep } from './helpers/qa.js';

/**
 * T5610 — REAL BROWSER (chromium) proof for "tap the spotlight to edit" + the override
 * hint, driven through a dev-only harness (/overlaydiag-t5610.html) that mounts the REAL
 * HighlightOverlay + REAL OverrideHint and mirrors OverlayModeView's T5610 glue against a
 * REAL <video>.
 *
 * jsdom gives false confidence for pointer/overlay changes (T5380/T5570 shipped
 * non-working "fixes" that passed jsdom), so the acceptance criteria are proven here on
 * BOTH a coarse (touch/mobile) and a fine (mouse/desktop) pointer.
 *
 * Acceptance-criterion map (task doc):
 *   AC1 tap-inside enters edit; tap-inside again dismisses; tracking stays on  -> test 1
 *   AC2 no drag stolen while editing; tap OUTSIDE the circle drives tap-nav    -> tests 2,3
 *   AC3 toggle-OFF free-edit path unchanged (no enter target)                  -> test 4
 *   AC4 hint names both paths, shows until first use, then fades + stays gone  -> test 5
 *   AC5 desktop + mobile parity; >=44px touch targets; no h-overflow           -> tests 6,7
 *
 * The 640x360 sample MP4 is generated by ffmpeg in beforeAll (not committed).
 * Run: cd src/frontend && npx playwright test e2e/T5610-manual-override.qa.spec.js
 */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SAMPLE = path.resolve(__dirname, '..', 'public', 'overlaydiag-sample.mp4');
const HARNESS = 'http://localhost:5173/overlaydiag-t5610.html';

const BODY = '[data-testid="highlight-body"]';
const ENTER_HIT = '[data-testid="highlight-enter-hit"]';
const CORNER_SE = '[data-testid="highlight-corner-se"]';
const CORNER_NW = '[data-testid="highlight-corner-nw"]';
const HINT = '[data-testid="override-hint"]';
const TOGGLE = '[data-testid="toggle-player-boxes"]';
const CONTAINER = '[data-testid="video-container"]';

test.beforeAll(() => {
  if (!existsSync(SAMPLE)) {
    execSync(
      `ffmpeg -y -f lavfi -i testsrc=duration=3:size=640x360:rate=30 -pix_fmt yuv420p -movflags +faststart "${SAMPLE}"`,
      { stdio: 'ignore' }
    );
  }
});

test.afterAll(() => {
  if (existsSync(SAMPLE)) unlinkSync(SAMPLE);
});

async function centerOf(locator) {
  const b = await locator.boundingBox();
  if (!b) throw new Error('element not visible');
  return { x: b.x + b.width / 2, y: b.y + b.height / 2, w: b.width, h: b.height };
}

/** A stationary tap (down + up, no move) at a point -> counts as a TAP. */
async function tapAt(page, x, y) {
  await page.mouse.move(x, y);
  await page.mouse.down();
  await page.mouse.up();
  await page.waitForTimeout(60);
}

/** A real drag by (dx,dy) from a locator's center. */
async function dragFrom(page, locator, dx, dy) {
  const c = await centerOf(locator);
  await page.mouse.move(c.x, c.y);
  await page.mouse.down();
  await page.mouse.move(c.x + dx, c.y + dy, { steps: 8 });
  await page.mouse.up();
  await page.waitForTimeout(60);
}

async function tapCircle(page) {
  const c = await centerOf(page.locator(BODY));
  await tapAt(page, c.x, c.y);
}

function suite(label, contextOpts) {
  test.describe(`T5610 manual override — ${label}`, () => {
    test.use(contextOpts);

    // AC1
    test('1) tap inside the circle enters edit; tap again dismisses; tracking stays on', async ({ page }) => {
      await page.goto(HARNESS);
      await expect(page.locator(BODY)).toBeVisible();
      // Tracking ON, display-only: enter target present, no edit controls yet.
      await expect(page.locator(ENTER_HIT)).toHaveCount(1);
      await expect(page.locator(CORNER_SE)).toHaveCount(0);

      // Tap inside -> edit controls appear, tracking layer stays ON (label unchanged).
      await tapCircle(page);
      await expect(page.locator(CORNER_SE)).toBeVisible();
      await expect(page.locator(CORNER_NW)).toBeVisible();
      await expect(page.locator(ENTER_HIT)).toHaveCount(0);
      await expect(page.locator(TOGGLE)).toHaveText('Tracking: ON');
      await expect(page.locator(BODY)).toBeVisible(); // circle still visible throughout
      await saveEvidence(page, `criterion-1-tap-enters-edit-${label}`);

      // Tap inside again -> dismiss back to display-only.
      await tapCircle(page);
      await expect(page.locator(CORNER_SE)).toHaveCount(0);
      await expect(page.locator(ENTER_HIT)).toHaveCount(1);
      await saveEvidence(page, `criterion-1-tap-again-dismisses-${label}`);
    });

    // AC2 — the T5570 drag-guard: a move drag while editing must not scrub/toggle the video.
    test('2) no drag is stolen while editing (circle moves, video does not seek/play)', async ({ page }) => {
      await page.goto(HARNESS);
      await tapCircle(page); // enter edit
      await expect(page.locator(CORNER_SE)).toBeVisible();

      const before = await centerOf(page.locator(BODY));
      const t0 = await page.evaluate(() => document.querySelector('video').currentTime);
      const paused0 = await page.evaluate(() => document.querySelector('video').paused);

      await dragFrom(page, page.locator(BODY), 60, 40);

      const after = await centerOf(page.locator(BODY));
      const t1 = await page.evaluate(() => document.querySelector('video').currentTime);
      const paused1 = await page.evaluate(() => document.querySelector('video').paused);

      expect(Math.round(after.x - before.x), 'circle moved with the drag').toBeGreaterThan(20);
      expect(t1, 'currentTime unchanged during circle drag').toBeCloseTo(t0, 3);
      expect(paused1, 'still paused (tap-nav yielded)').toBe(paused0);
      expect(await page.locator(CORNER_SE).isVisible(), 'still editing after a move').toBe(true);
      await saveEvidence(page, `criterion-2-drag-not-stolen-${label}`);
    });

    // AC2 — hit-priority: a tap OUTSIDE the circle is NOT captured by the circle; it drives
    // tap-nav (and exits edit). Proves inside-wins / outside-passes.
    test('3) tap outside the circle does not enter edit; drives tap-nav', async ({ page }) => {
      await page.goto(HARNESS);
      // Display-only. Tap a far corner of the video (outside the circle).
      const cbox = await page.locator(CONTAINER).boundingBox();
      await tapAt(page, cbox.x + 12, cbox.y + 12);
      // Did not enter edit...
      await expect(page.locator(CORNER_SE)).toHaveCount(0);
      // ...and tap-nav fired (video started playing).
      await page.waitForFunction(() => !document.querySelector('video').paused, null, { timeout: 3000 });
      expect(await page.evaluate(() => document.querySelector('video').paused)).toBe(false);
    });

    // AC3 — toggle-OFF free-edit path is unchanged (editable without a tap, no enter target).
    test('4) toggle tracking OFF = free edit, no tap-to-enter target', async ({ page }) => {
      await page.goto(HARNESS);
      await page.locator(TOGGLE).click(); // tracking OFF
      await expect(page.locator(TOGGLE)).toHaveText('Tracking: OFF');
      await expect(page.locator(CORNER_SE)).toBeVisible(); // editable immediately
      await expect(page.locator(ENTER_HIT)).toHaveCount(0); // no tap-toggle target
      await saveEvidence(page, `criterion-3-toggle-off-free-edit-${label}`);
    });

    // AC5 — >=44px touch targets on coarse; compact on fine.
    test('5) corner handles are >=44px on coarse pointers', async ({ page }) => {
      await page.goto(HARNESS);
      await tapCircle(page);
      await expect(page.locator(CORNER_SE)).toBeVisible();
      const box = await page.locator(CORNER_SE).boundingBox();
      if (label === 'coarse (touch)') {
        expect(box.width, 'corner hit width').toBeGreaterThanOrEqual(44);
        expect(box.height, 'corner hit height').toBeGreaterThanOrEqual(44);
      } else {
        expect(box.width, 'fine pointer keeps compact sizing').toBeLessThan(44);
      }
    });
  });
}

suite('fine (mouse)', {});
suite('coarse (touch)', { hasTouch: true, isMobile: true, viewport: { width: 412, height: 915 } });

// AC4 — the discoverability hint. Device-agnostic, runs once (fine).
test.describe('T5610 override hint', () => {
  test('6) hint names both paths, shows until first override, then fades and stays gone', async ({ page }) => {
    await page.goto(HARNESS);
    // Shows on load (tracking ON, region visible, not yet overridden), naming BOTH paths.
    await expect(page.locator(HINT)).toBeVisible();
    await expect(page.locator(HINT)).toContainText('Tap the spotlight');
    await expect(page.locator(HINT)).toContainText('hide tracking');
    await saveEvidence(page, 'criterion-4-hint-shown');

    // First override (tap the circle) -> hint fades out and unmounts.
    await tapCircle(page);
    await expect(page.locator(HINT)).toHaveCount(0, { timeout: 2000 });
    await saveEvidence(page, 'criterion-4-hint-faded');

    // Exit edit; hint stays gone for the session (overrideUsed latched).
    await tapCircle(page);
    await expect(page.locator(BODY)).toBeVisible();
    await expect(page.locator(HINT)).toHaveCount(0);
  });

  // AC5 — desktop + mobile parity, no horizontal overflow on the changed surface.
  test('7) responsive: no horizontal overflow at 375px and desktop', async ({ page }) => {
    await page.goto(HARNESS);
    await expect(page.locator(BODY)).toBeVisible();
    await responsiveSweep(page);
  });
});
