import { test, expect } from '@playwright/test';
import { execSync } from 'node:child_process';
import { existsSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { skipOnDeployedTarget } from './helpers/targetEnv.js';

/**
 * T5860 — REAL BROWSER (chromium, desktop) proof that CollectionPlayer is modal.
 *
 * Driven through a dev-only harness (/collectionplayerdiag.html) that mounts the
 * REAL CollectionPlayer over a field of REAL interactive tiles (hover + click
 * handlers), mimicking the Highlight Reels tiles/carousel behind the player. On desktop
 * the panel's `md:inset-12` leaves a ~48px gutter ring around the player.
 *
 * Proven here:
 *   1. A point in the desktop gutter (x=8, y=mid) resolves to the BACKDROP, not a
 *      tile button (pre-fix it resolved to a tile — the reported pass-through bug).
 *   2. Hovering the gutter fires NO tile hover/reveal.
 *   3. Clicking the gutter fires NO tile click AND does not close the player
 *      (project rule: misclicks must not dismiss).
 *
 * The 360x640 portrait sample MP4 is generated by ffmpeg in beforeAll (not committed).
 * Run: cd src/frontend && npx playwright test e2e/T5860-collectionplayer-modal-backdrop.qa.spec.js
 */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SAMPLE = path.resolve(__dirname, '..', 'public', 'collectionplayerdiag-sample.mp4');
const HARNESS = '/collectionplayerdiag.html';

const DIALOG = '[role="dialog"]';
const STATUS = '[data-testid="status"]';

// Desktop viewport so md:inset-12 applies and the gutter ring exists.
test.use({ viewport: { width: 1280, height: 800 } });

test.beforeAll(() => {
  if (!existsSync(SAMPLE)) {
    execSync(
      `ffmpeg -y -f lavfi -i testsrc=duration=3:size=360x640:rate=30 -pix_fmt yuv420p -movflags +faststart "${SAMPLE}"`,
      { stdio: 'ignore' },
    );
  }
});

test.afterAll(() => {
  if (existsSync(SAMPLE)) unlinkSync(SAMPLE);
});

async function openPlayer(page) {
  await page.goto(HARNESS);
  // Wait on elements present in BOTH the buggy and fixed player (the harness
  // status + the player's <video>), so the pre-fix run fails on the actual
  // assertion below rather than hanging on a selector the fix introduces.
  await page.waitForSelector(STATUS);
  await page.waitForSelector('video');
}

test('desktop gutter point resolves to the backdrop, not a tile', async ({ page }) => {
  // /collectionplayerdiag.html is a Vite-dev-only harness page: not an input to the
  // production build, so on a deployed target this RELATIVE path resolves against the
  // Pages origin and the SPA catch-all serves index.html instead — the harness never mounts.
  skipOnDeployedTarget(test, 'drives the dev-only /collectionplayerdiag.html harness page, which does not exist in a production BUILD');
  await openPlayer(page);

  const hit = await page.evaluate(() => {
    const el = document.elementFromPoint(8, window.innerHeight / 2); // gutter, outside the panel
    return {
      testid: el?.getAttribute('data-testid'),
      tag: el?.tagName,
      cls: el?.className?.toString().slice(0, 120),
    };
  });

  // PASS (post-fix): the backdrop. FAIL (pre-fix): a bg-tile button underneath.
  expect(hit.testid).toBe('collection-player-backdrop');
  expect(hit.testid).not.toBe('bg-tile');
});

test('hovering the gutter triggers no tile hover/reveal', async ({ page }) => {
  skipOnDeployedTarget(test, 'drives the dev-only /collectionplayerdiag.html harness page, which does not exist in a production BUILD');
  await openPlayer(page);

  await page.mouse.move(8, 400);
  await page.mouse.move(8, 401); // nudge so mouseenter would fire if it reached a tile
  await page.waitForTimeout(80);

  const lastHover = await page.locator(STATUS).getAttribute('data-last-hover');
  expect(lastHover).toBe('none');
});

test('clicking the gutter fires no tile click and does not close the player', async ({ page }) => {
  skipOnDeployedTarget(test, 'drives the dev-only /collectionplayerdiag.html harness page, which does not exist in a production BUILD');
  await openPlayer(page);

  await page.mouse.click(8, 400);
  await page.waitForTimeout(80);

  const lastClick = await page.locator(STATUS).getAttribute('data-last-click');
  expect(lastClick).toBe('none');

  // Backdrop must swallow the click without dismissing — dialog still open.
  await expect(page.locator(DIALOG)).toBeVisible();
});

test('completes the modal contract: role/aria, scroll lock, focus trap, aspect skeleton', async ({ page }, testInfo) => {
  skipOnDeployedTarget(test, 'drives the dev-only /collectionplayerdiag.html harness page, which does not exist in a production BUILD');
  await openPlayer(page);

  const contract = await page.evaluate(() => {
    const dialog = document.querySelector('[role="dialog"]');
    const backdrop = document.querySelector('[data-testid="collection-player-backdrop"]');
    return {
      ariaModal: dialog?.getAttribute('aria-modal'),
      backdropAriaHidden: backdrop?.getAttribute('aria-hidden'),
      bodyOverflow: document.body.style.overflow,
      focusInsideDialog: !!dialog && dialog.contains(document.activeElement),
    };
  });

  expect(contract.ariaModal).toBe('true');
  expect(contract.backdropAriaHidden).toBe('true');
  expect(contract.bodyOverflow).toBe('hidden'); // background scroll locked
  expect(contract.focusInsideDialog).toBe(true); // focus trapped inside the dialog

  // Evidence the open state is deterministic (full player, black gutter — no
  // "slice of video"): capture a screenshot for the QA record.
  const shot = await page.screenshot();
  await testInfo.attach('player-open-desktop', { body: shot, contentType: 'image/png' });
});
