import { test, expect } from '@playwright/test';
import { openGameDetailsDisclosure } from './helpers/gameDetails.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { saveEvidence, assertNoHorizontalOverflow } from './helpers/qa.js';

/**
 * T7920 — Mobile clip-save live-drive AUDIT (add_clip_opened -> saved clip).
 *
 * The decisive 2026-08-27 drop-off is durable-upload -> first clip, and the
 * first-ever successful mobile uploader (mostafaali452010) fired `add_clip_opened`
 * then saved NOTHING and left. Nobody had driven the full mobile clip-save path
 * end-to-end since T7540 (tag trap), T7850 (no-sport Add Clip warning), and T7590
 * (mobile Add Game) landed. This spec closes that gap.
 *
 * It is SELF-CONTAINED (no pre-seeded real account): it isolates a disposable
 * guest via the X-User-ID / test-login bypass, sets `isAuthenticated` so the
 * requireAuth-gated Add Clip button opens the form (a guest otherwise gets the
 * login modal — see AnnotateContainer.handleAddClipFromButton), uploads the short
 * local test video, then drives the REAL mobile inline Add Clip form
 * (AnnotateFullscreenOverlay layout="inline") at the reported iPhone viewports.
 *
 * A fresh guest profile is `sport = 'no_sport'` (T7850), so the form's Tags block
 * renders <NoSportTagWarning> — this is the first LIVE drive of that surface.
 *
 * Audit checklist (each with screenshot evidence via saveEvidence):
 *   1. Add Clip form fully reachable/operable at 320px (no control off-viewport)
 *   2. Tag input: T7540 fix on mobile — teammate typed WITHOUT Enter still saves
 *   3. NoSportTagWarning renders in the mobile Add Clip Tags block
 *   4. Save button reachable (incl. input focused, simulating keyboard); round-trip
 *      completes with a real raw_clips row; failure states are visible
 *   5. clip_save_attempted (T7510 clips_attempted counter) fires — verified out of
 *      band against user_actions by the runner (see T7920 status/verdict).
 *
 * Real browser required (T5380 lesson: jsdom lies on pointer/viewport). Runs on the
 * chromium engine at real iPhone viewport sizes; the true iOS soft-keyboard is NOT
 * emulated (documented limitation, not a pass) — item 4 focuses the input to
 * approximate it and the verdict flags the real-device residue.
 *
 * Run (inside a /dotask container, stack already up):
 *   T7920_USER_ID=e2e_t7920_<stamp> npx playwright test e2e/T7920-mobile-clip-save-audit.qa.spec.js \
 *     --project=chromium --reporter=line
 */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TEST_DATA_DIR = path.resolve(__dirname, '../../../formal annotations/test.short');
// A UNIQUE video per run (T7920_VIDEO, generated by the runner) is required so the
// upload creates a genuinely FRESH game: the app dedups uploads by content hash, so
// re-uploading the same file resolves to the earlier game (a resumed, non-fresh
// state where the mobile create-clip save path does not fire). Falls back to the
// shared fixture for a one-off local run.
const TEST_VIDEO = process.env.T7920_VIDEO || path.join(TEST_DATA_DIR, 'wcfc-carlsbad-trimmed.mp4');

// Deterministic-per-run guest id: the runner passes the SAME value to the
// post-run user_actions counter query, so clip_save_attempted can be verified.
const TEST_USER_ID = process.env.T7920_USER_ID || `e2e_t7920_${Date.now()}`;
const apiBase = process.env.E2E_API_BASE || '/api';

// The task's exact reported matrix (both portrait iPhone-class).
const PORTRAIT_VIEWPORTS = [
  { name: '320x568', width: 320, height: 568 }, // iPhone SE (1st gen) class
  { name: '375x667', width: 375, height: 667 }, // iPhone 6/7/8/SE2 class
];

// Distinct seek times (seconds) so each viewport's created clip lands in its own
// gap: default clip window is [t-9, t+3], so 20/50/78 never overlap.
const SEEK_BY_VIEWPORT = { '320x568': 78, '375x667': 62 };

test.describe.configure({ mode: 'serial', timeout: 480_000 });

/** Isolate a disposable authenticated guest (headers + test-login + auth gate). */
async function setupAuthedGuest(page) {
  await page.setExtraHTTPHeaders({ 'X-User-ID': TEST_USER_ID, 'X-Test-Mode': 'true' });
  // R2 presigned PUT/GET must not carry X-Test-Mode (CORS preflight).
  await page.route(/r2\.cloudflarestorage\.com/, async (route) => {
    const headers = { ...route.request().headers() };
    delete headers['x-test-mode'];
    await route.continue({ headers });
  });
  // Use domcontentloaded, NOT the default 'load': the SPA bootstrap keeps a
  // fetch in flight (checkAdmin / prefetch), so the window 'load' event can lag
  // indefinitely and a default goto/reload would hang to the test timeout.
  await page.goto('/', { waitUntil: 'domcontentloaded' });
  await page.evaluate(async () => {
    await fetch('/api/auth/test-login', {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json', 'X-Test-Mode': 'true' },
    });
  });
  // Bypass the frontend auth gate so requireAuth() runs the Add Clip action
  // instead of popping the login modal (faithful to an AUTHENTICATED mobile user).
  await page.evaluate(async () => {
    const { useAuthStore } = await import('/src/stores/authStore.js');
    useAuthStore.setState({ isAuthenticated: true, email: 't7920@e2e.local', showAuthModal: false });
  });
  await page.reload({ waitUntil: 'domcontentloaded' });
  // Wait for the home to hydrate (the Add Game entry point renders).
  await expect(page.locator('button:has-text("Add Game")').first()).toBeVisible({ timeout: 20000 });
}

const step = (m) => console.log(`[T7920:step] ${m}`);

/** Upload the short test video via the Add Game modal, land in Annotate. */
async function uploadGameAndEnterAnnotate(page) {
  // Games tab is best-effort (a zero-games home may not surface it); the top-level
  // "Add Game" CTA is the reliable entry point.
  step('click Games tab (best-effort)');
  await page.locator('button:has-text("Games")').first().click({ timeout: 3000 }).catch(() => {});
  await page.waitForTimeout(300);
  step('click Add Game');
  await page.locator('button:has-text("Add Game")').first().click();
  await openGameDetailsDisclosure(page);
  await expect(page.getByPlaceholder('e.g., Carlsbad SC')).toBeVisible({ timeout: 8000 });
  step('Add Game modal open');

  await page.getByPlaceholder('e.g., Carlsbad SC').fill('T7920 Audit');
  const today = new Date().toISOString().split('T')[0];
  await page.locator('input[type="date"]').fill(today);
  await page.getByRole('button', { name: 'Home' }).click({ force: true });

  const videoInput = page.locator('form input[type="file"][accept*="video"]');
  await expect(videoInput).toBeAttached({ timeout: 10000 });
  step('setInputFiles video');
  await videoInput.setInputFiles(TEST_VIDEO);
  await page.waitForTimeout(500);
  // Neutralize the client-side upload paywall: an isolated test guest has 0
  // credits and does NOT get the real-user starter grant, so once the balance
  // loads GameDetailsModal.handleSubmit opens Buy Credits instead of creating the
  // game (the backend still authorizes the guest upload — proven live). Seeding a
  // high balance keeps the drive on the create path deterministically. This is a
  // HARNESS-only bypass of a real-user affordance, not under test here.
  await page.evaluate(async () => {
    const { useCreditStore } = await import('/src/stores/creditStore.js');
    useCreditStore.setState({ balance: 1_000_000, loaded: true });
  });
  // The submit button is the LAST "Add Game" button in the modal footer; scope to
  // the enabled one and bound the click so a mid-transition relabel can't hang the
  // whole test. Fall back to submitting the form via Enter.
  const createButton = page.locator('form button:has-text("Add Game")').last();
  await expect(createButton).toBeEnabled({ timeout: 8000 });
  step('click Create (submit Add Game)');
  const clicked = await createButton.click({ timeout: 12000 }).then(() => true).catch(() => false);
  if (!clicked) {
    step('submit click did not settle; retry force + Enter');
    await createButton.click({ force: true, timeout: 8000 }).catch(() => {});
    await page.getByPlaceholder('e.g., Carlsbad SC').press('Enter').catch(() => {});
  }
  step('submitted; waiting for annotate video to mount');
  // gameId is read later from the first clip-save payload (game_id) — more robust
  // than racing a specific create-request response shape.

  // Wait for the annotate <video> to mount and become seekable.
  await expect(async () => {
    const video = page.locator('video').first();
    await expect(video).toBeVisible();
    expect(await video.evaluate((v) => !!v.src)).toBeTruthy();
  }).toPass({ timeout: 120000, intervals: [1000, 2000, 5000] });

  // Do NOT block on the R2 upload finalizing: the game_id exists from
  // onGameCreated mid-upload and save_raw_clip tolerates a still-pending file
  // (T1540 annotate-during-upload) — the local blob <video> is already seekable.
  // This mirrors mostafaali452010's real flow (add_clip_opened right after the
  // upload landed) and keeps the drive fast/deterministic instead of hostage to
  // variable in-container R2 finalize latency. Give it a short grace only.
  const uploadingButton = page.locator('button:has-text("Uploading video")');
  await page.waitForTimeout(2000);
  await uploadingButton.isVisible().then((v) => v && expect(uploadingButton).toBeHidden({ timeout: 30000 }).catch(() => {})).catch(() => {});

  step('video visible; waiting for seekable');
  await page.waitForFunction(() => {
    const v = document.querySelector('video');
    return !!v && v.readyState >= 2 && v.seekable.length > 0 && v.duration > 0;
  }, undefined, { timeout: 120000 });
  step('video seekable — annotate ready');
}

/**
 * Open the mobile inline Add Clip form. The non-fullscreen "Add Clip" button
 * renders ONLY in the NONE selection state; when the playhead sits inside a clip
 * the sidebar edits it and the button hides. The shared dev profile can carry
 * pre-existing clips, so scan candidate seek times (preferring the caller's) until
 * the playhead lands in a clip-free gap and the button shows.
 */
async function openMobileAddClipForm(page, preferredSeek) {
  const candidates = [preferredSeek, 78, 70, 62, 33, 15, 85, 8];
  const addBtn = page.locator('button[title="Add clip ending at current time (A)"]:visible').first();
  for (const t of candidates) {
    const landed = await page.locator('video').first().evaluate((v, tt) => {
      if (!v.paused) v.pause();
      v.currentTime = tt;
      return v.currentTime;
    }, t);
    if (Math.abs(landed - t) > 2) { await page.waitForTimeout(400); continue; }
    await page.waitForTimeout(700); // auto-select re-evaluates (deselects in a gap)
    if (await addBtn.isVisible().catch(() => false)) {
      await addBtn.click();
      const form = page.locator('[data-add-clip-form]:visible');
      await expect(form).toBeVisible({ timeout: 5000 });
      return form;
    }
  }
  throw new Error('[T7920] no clip-free gap found to open the mobile Add Clip form');
}

let gameId;

test.beforeAll(() => {
  if (!fs.existsSync(TEST_VIDEO)) throw new Error(`Test video not found: ${TEST_VIDEO}`);
  console.log(`[T7920] guest user id: ${TEST_USER_ID}`);
});

test('mobile clip-save live-drive audit (320x568 + 375x667)', async ({ page }) => {
  step('setupAuthedGuest start');
  await setupAuthedGuest(page);
  step('setupAuthedGuest done');
  await page.setViewportSize({ width: 375, height: 667 });
  await uploadGameAndEnterAnnotate(page);

  const savedClipIds = [];

  for (const vp of PORTRAIT_VIEWPORTS) {
    await page.setViewportSize({ width: vp.width, height: vp.height });
    await page.waitForTimeout(300);

    const form = await openMobileAddClipForm(page, SEEK_BY_VIEWPORT[vp.name]);

    // --- Criterion 1: form fully reachable/operable, no horizontal overflow ----
    await assertNoHorizontalOverflow(page);
    const saveBtn = form.locator('button.bg-green-600:has-text("Save")');
    await expect(saveBtn).toBeVisible();
    // Save control must be within the viewport (scrollable to; not clipped off).
    await saveBtn.scrollIntoViewIfNeeded();
    const saveBox = await saveBtn.boundingBox();
    expect(saveBox, 'Save button has a layout box').not.toBeNull();
    expect(saveBox.y).toBeGreaterThanOrEqual(0);
    expect(saveBox.y + saveBox.height).toBeLessThanOrEqual(vp.height + 1);
    await saveEvidence(page, `criterion-1-form-reachable-${vp.name}`);

    // --- Criterion 3: NoSportTagWarning renders in the Tags block --------------
    // A fresh guest profile is no_sport (T7850) -> the amber prompt replaces the
    // sport TagSelector. If a sport WAS chosen this asserts nothing false — we
    // record which branch actually rendered.
    // T7922: the full (portrait) no_sport prompt is now the ACTIONABLE inline
    // sport picker ("Pick your sport to tag this clip" + a Change-sport select),
    // not the old dead "top bar" prose. The compact landscape variant (asserted
    // later) still shows the instructional prose (deferred).
    const noSportWarn = form.getByText('Pick your sport to tag this clip');
    const hasNoSport = await noSportWarn.isVisible().catch(() => false);
    expect(hasNoSport, 'fresh guest should hit the no_sport inline sport picker branch').toBeTruthy();
    await saveEvidence(page, `criterion-3-nosport-warning-${vp.name}`);

    // --- Criterion 2: teammate tag typed WITHOUT Enter must not dead-end Save --
    // Teammates are Team-layer only, so switch the clip to Team to reveal the input.
    await form.getByRole('radio', { name: 'Team layer' }).click();
    const tagInput = form.getByPlaceholder('Tag a teammate...');
    await expect(tagInput).toBeVisible({ timeout: 5000 });
    const PENDING_TAG = `QA T7920 ${vp.name}`;
    await tagInput.fill(PENDING_TAG); // deliberately NO Enter — the trap condition
    // Criterion 4 (keyboard proxy): with the tag input focused (soft keyboard would
    // be up on a real phone), the Save button must still be reachable.
    await saveBtn.scrollIntoViewIfNeeded();
    await saveEvidence(page, `criterion-2-4-pending-tag-focused-${vp.name}`);

    // --- Criterion 4: Save round-trip completes, tag auto-committed ------------
    const [saveResp] = await Promise.all([
      page.waitForResponse(
        (r) => r.url().includes('/api/clips/raw/save') && r.request().method() === 'POST',
        { timeout: 15000 },
      ),
      saveBtn.click(),
    ]);
    expect(saveResp.ok(), `save POST ok at ${vp.name}`).toBeTruthy();
    const body = await saveResp.json();
    expect(body.raw_clip_id, `raw_clip_id returned at ${vp.name}`).toBeTruthy();
    savedClipIds.push(body.raw_clip_id);

    // T7540 on mobile: the pending (un-Entered) teammate text was auto-committed.
    const sent = saveResp.request().postDataJSON();
    if (gameId === undefined) gameId = sent.game_id; // robust gameId source
    expect(sent.tagged_teammates, `pending tag auto-committed at ${vp.name}`).toContain(PENDING_TAG);
    // The old OK-only dead-end dialog must never appear.
    await expect(page.getByText('Tag not submitted')).toHaveCount(0);
    await saveEvidence(page, `criterion-4-saved-${vp.name}`);
  }

  // --- Criterion 4 (durable proof): the raw_clips rows really exist ------------
  const loadRes = await page.request.get(`${apiBase}/games/${gameId}/load`);
  expect(loadRes.ok()).toBeTruthy();
  const loaded = await loadRes.json();
  const annotations = loaded.game?.annotations || loaded.annotations || [];
  const rawIds = new Set(annotations.map((a) => a.rawClipId ?? a.raw_clip_id ?? a.id));
  for (const id of savedClipIds) {
    expect([...rawIds].map(String), 'saved clip present in /load annotations').toContain(String(id));
  }
  console.log(`[T7920] saved raw_clip ids: ${savedClipIds.join(', ')}; /load annotations: ${annotations.length}`);

  // --- Criterion 3 (compact variant): landscape-inline NoSportTagWarning -------
  // The compact amber prompt only renders in the mobile-fullscreen LANDSCAPE scrub
  // bar (AnnotateFullscreenOverlay layout="landscape-inline"). annotateFullscreen
  // is CSS-based app state (no browser Fullscreen API), so it drives headless.
  await page.setViewportSize({ width: 667, height: 375 }); // landscape phone
  await page.waitForTimeout(300);
  // BEST-EFFORT: the landscape-fullscreen scrub bar auto-hides its controls, which
  // makes the NONE-state Add Clip button flaky to reach under emulation. The
  // compact NoSportTagWarning is component-tested; this live attempt is a bonus, so
  // a miss is logged (real-device gap) rather than failing the core audit.
  let compactVerified = false;
  const fsBtn = page.locator('button[title="Fullscreen"]:visible').first();
  if (await fsBtn.isVisible({ timeout: 2000 }).catch(() => false)) {
    await fsBtn.click({ timeout: 3000 }).catch(() => {});
    await page.waitForTimeout(500);
    const addBtnFs = page.locator('button[title="Add clip ending at current time (A)"]:visible').first();
    for (const t of [33, 15, 25, 45]) {
      await page.locator('video').first().evaluate((v, tt) => { if (!v.paused) v.pause(); v.currentTime = tt; }, t).catch(() => {});
      // Tap the video to reveal the auto-hiding fullscreen controls (bounded so a
      // fullscreen actionability stall can never hang the suite).
      await page.locator('video').first().click({ position: { x: 40, y: 30 }, timeout: 2500 }).catch(() => {});
      await page.waitForTimeout(400);
      if (await addBtnFs.isVisible({ timeout: 1000 }).catch(() => false)) {
        await addBtnFs.click({ timeout: 2500 }).catch(() => {});
        break;
      }
    }
    const lsForm = page.locator('[data-add-clip-form]:visible');
    if (await lsForm.getByText('Set your sport (top bar) for tags').isVisible({ timeout: 3000 }).catch(() => false)) {
      await assertNoHorizontalOverflow(page);
      await saveEvidence(page, 'criterion-3-nosport-warning-compact-landscape-667x375');
      compactVerified = true;
    }
  }
  console.log(compactVerified
    ? '[T7920] landscape-inline compact NoSportTagWarning verified live'
    : '[T7920] NOTE: compact NoSportTagWarning not driven under emulation (auto-hiding fullscreen controls) — covered by component tests; needs a real-device pass');
});
