import { useState, useEffect, useCallback } from 'react';
import { X, Upload, Film } from 'lucide-react';
import { StarRating, TagSelector } from './shared';
import { generateClipName } from '../modes/annotate/constants/soccerTags';
import { ensureUniqueName, getExistingNamesForGame } from '../utils/uniqueName';

/**
 * UploadClipModal - Modal for uploading a clip with metadata
 *
 * Shows after user selects a file, allowing them to set:
 * - Name (auto-generates from rating+tags if not manually entered)
 * - Rating (1-5 stars)
 * - Tags (multi-select)
 * - Notes (optional)
 *
 * @param {boolean} isOpen - Whether modal is visible
 * @param {function} onClose - Callback to close modal
 * @param {function} onUpload - Callback with { file, name, rating, tags, notes }
 * @param {File} selectedFile - The File object selected by user
 * @param {Array} existingClips - Existing clips for unique name validation
 */
export function UploadClipModal({
  isOpen,
  onClose,
  onUpload,
  selectedFile,
  existingClips = [],
}) {
  // Form state
  const [name, setName] = useState('');
  const [isNameManual, setIsNameManual] = useState(false);
  const [rating, setRating] = useState(3);
  const [selectedTags, setSelectedTags] = useState([]);
  const [notes, setNotes] = useState('');
  const [isUploading, setIsUploading] = useState(false);

  // Reset form when modal opens with new file
  useEffect(() => {
    if (isOpen && selectedFile) {
      // Initialize name from filename (without extension)
      const baseName = selectedFile.name.replace(/\.[^/.]+$/, '');
      setName(baseName);
      setIsNameManual(false);
      setRating(3);
      setSelectedTags([]);
      setNotes('');
      setIsUploading(false);
    }
  }, [isOpen, selectedFile]);

  // Auto-generate name from rating+tags unless user manually edited
  useEffect(() => {
    if (!isNameManual && selectedTags.length > 0) {
      const generated = generateClipName(rating, selectedTags);
      if (generated) {
        setName(generated);
      }
    }
  }, [rating, selectedTags, isNameManual]);

  // Handlers
  const handleNameChange = useCallback((e) => {
    setName(e.target.value);
    setIsNameManual(true);
  }, []);

  const handleRatingChange = useCallback((newRating) => {
    setRating(newRating);
  }, []);

  const handleTagToggle = useCallback((tagName) => {
    setSelectedTags(prev => {
      if (prev.includes(tagName)) {
        return prev.filter(t => t !== tagName);
      }
      return [...prev, tagName];
    });
  }, []);

  const handleNotesChange = useCallback((e) => {
    setNotes(e.target.value.slice(0, 280));
  }, []);

  const handleUpload = useCallback(async () => {
    if (!selectedFile || !name.trim()) return;

    setIsUploading(true);

    // Ensure unique name (for clips without a game)
    const existingNames = getExistingNamesForGame(existingClips, null);
    const uniqueName = ensureUniqueName(name.trim(), existingNames);

    try {
      await onUpload({
        file: selectedFile,
        name: uniqueName,
        rating,
        tags: selectedTags,
        notes: notes.trim()
      });
      onClose();
    } catch (err) {
      console.error('[UploadClipModal] Upload failed:', err);
      setIsUploading(false);
    }
  }, [selectedFile, name, rating, selectedTags, notes, existingClips, onUpload, onClose]);

  const handleKeyDown = useCallback((e) => {
    if (e.key === 'Enter' && !e.shiftKey && name.trim()) {
      e.preventDefault();
      handleUpload();
    }
    if (e.key === 'Escape') {
      onClose();
    }
  }, [handleUpload, onClose, name]);

  if (!isOpen || !selectedFile) return null;

  // File info
  const fileSizeMB = (selectedFile.size / (1024 * 1024)).toFixed(2);
  const isAutoGenerated = !isNameManual && selectedTags.length > 0;

  return (
    <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50">
      <div
        className="bg-gray-800 rounded-lg w-full max-w-lg max-h-[90vh] flex flex-col border border-gray-700"
        onKeyDown={handleKeyDown}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-gray-700">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <Upload size={20} />
            Upload Clip
          </h2>
          <button
            onClick={onClose}
            className="p-1 hover:bg-gray-700 rounded transition-colors"
            disabled={isUploading}
          >
            <X size={20} className="text-gray-400" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {/* File info */}
          <div className="bg-gray-900/50 rounded-lg p-3 flex items-center gap-3">
            <Film size={24} className="text-purple-400" />
            <div className="flex-1 min-w-0">
              <div className="text-white font-medium truncate">{selectedFile.name}</div>
              <div className="text-sm text-gray-400">{fileSizeMB} MB</div>
            </div>
          </div>

          {/* Name */}
          <div>
            <label className="block text-sm text-gray-400 mb-1">
              Clip Name {isAutoGenerated && <span className="text-gray-500">(auto)</span>}
            </label>
            <input
              type="text"
              value={name}
              onChange={handleNameChange}
              placeholder="Enter clip name..."
              className="w-full px-3 py-2 bg-gray-700 text-white rounded-lg border border-gray-600 focus:border-purple-500 focus:outline-none"
              autoFocus
            />
          </div>

          {/* Rating */}
          <div>
            <label className="block text-sm text-gray-400 mb-2">Rating</label>
            <StarRating rating={rating} onRatingChange={handleRatingChange} size={24} />
          </div>

          {/* Tags */}
          <div>
            <label className="block text-sm text-gray-400 mb-2">Tags</label>
            <div className="max-h-48 overflow-y-auto pr-2">
              <TagSelector selectedTags={selectedTags} onTagToggle={handleTagToggle} compact />
            </div>
          </div>

          {/* Notes */}
          <div>
            <label className="block text-sm text-gray-400 mb-1">
              Notes <span className="text-gray-500">({notes.length}/280)</span>
            </label>
            <textarea
              value={notes}
              onChange={handleNotesChange}
              placeholder="Add notes about this clip..."
              rows={2}
              className="w-full px-3 py-2 bg-gray-700 text-white rounded-lg border border-gray-600 focus:border-purple-500 focus:outline-none resize-none"
            />
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-gray-700 flex gap-3">
          <button
            onClick={onClose}
            disabled={isUploading}
            className="flex-1 px-4 py-2 bg-gray-700 hover:bg-gray-600 disabled:bg-gray-700 text-white rounded-lg transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleUpload}
            disabled={isUploading || !name.trim()}
            className="flex-1 px-4 py-2 bg-purple-600 hover:bg-purple-700 disabled:bg-gray-600 text-white rounded-lg transition-colors flex items-center justify-center gap-2"
          >
            {isUploading ? (
              <>
                <span className="animate-spin">...</span>
                Uploading...
              </>
            ) : (
              <>
                <Upload size={16} />
                Upload
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

export default UploadClipModal;
