import { useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { VideoPlayer } from '../components/VideoPlayer';
import PlayerDetectionOverlay from '../modes/overlay/overlays/PlayerDetectionOverlay';
import '../index.css'; // Tailwind — .video-container / stage box classes need it

/**
 * T9100 — DEV-ONLY real-browser harness for player-detection box alignment.
 *
 * Both stages play the SAME 9:16 reel (`/t9100diag-9x16.mp4`, 1080x1920) with a
 * single detection box at the reel's true center (540, 960). They differ ONLY in
 * the `videoMetadata` fed to OverlayModeView's stage box AND to
 * PlayerDetectionOverlay's `useVideoDisplayRect` — exactly the value the T9100
 * bug corrupted:
 *
 *   - "fixed"  metadata = the reel's TRUE dims (1080x1920). This is what the fix
 *              guarantees: the null-blob branch no longer seeds workingVideo with
 *              metadata:null, so OverlayScreen's real loader populates the reel's
 *              own dimensions. Stage box aspect == the <video>'s rendered aspect,
 *              detection box lands ON the video content. (Equivalent to the cold-
 *              from-Drafts control path, which was never broken.)
 *   - "bug"    metadata = the SOURCE CLIP's landscape dims (1920x1080) — the
 *              banned silent fallback (effectiveOverlayMetadata -> framingMetadata)
 *              that ran when workingVideo carried a url but no metadata. The stage
 *              box stretches to 16:9 (the "canvas stretches past the video"
 *              symptom); the 9:16 video object-contains to a narrow centered
 *              strip; useVideoDisplayRect (fed the wrong 16:9 dims) places the box
 *              in the left ~56% of the wide panel, OFF the actual video content.
 *
 * The stage box class/style is mirrored verbatim from modes/OverlayModeView.jsx
 * `useAspectStage` branch. The bug stage is a live CONTROL: the spec asserts the
 * harness discriminates (bug stage's stage-aspect != video-aspect and its box is
 * offset), which proves the fixed stage's alignment is meaningful, not vacuous.
 *
 * The sample video is ffmpeg-generated by the Playwright spec and served via
 * page.route from disk (vite v5 caches its publicDir listing at startup, so a
 * file added after boot 404s — the T5590/T5676 lesson).
 */

// The reel's TRUE dimensions (portrait 9:16) — what a real exported reel is.
const REEL_META = { width: 1080, height: 1920 };
// The source clip's landscape dimensions — the wrong value the bug fell back to.
const SOURCE_CLIP_META = { width: 1920, height: 1080 };
// One detection box at the reel's true center, in the reel's own coordinate space.
const DETECTIONS = [{ x: 540, y: 960, width: 220, height: 300, confidence: 0.9 }];

const SRC = '/t9100diag-9x16.mp4';
const ZOOM = 1;
const PAN_OFFSET = { x: 0, y: 0 };
const NOOP_HANDLERS = {};

const STAGES = [
  { testId: 'stage-fixed', label: 'FIXED: reel metadata (1080x1920)', metadata: REEL_META },
  { testId: 'stage-bug', label: 'BUG: source-clip metadata (1920x1080)', metadata: SOURCE_CLIP_META },
];

function DetectionStage({ testId, label, metadata }) {
  const videoRef = useRef(null);

  // Mirrors modes/OverlayModeView.jsx useAspectStage branch verbatim: the stage
  // box's aspect-ratio comes from the (possibly wrong) metadata, exactly as
  // `effectiveOverlayMetadata` drives it in the real screen.
  const useAspectStage = metadata.width > 0 && metadata.height > 0;
  const stageBoxClass = useAspectStage
    ? 'relative bg-gray-900 rounded-lg overflow-hidden mx-auto w-full max-w-full lg:w-fit lg:h-[70vh] lg:max-h-[70vh]'
    : 'relative bg-gray-900 rounded-lg';
  const stageBoxStyle = useAspectStage ? { aspectRatio: `${metadata.width} / ${metadata.height}` } : undefined;

  return (
    <div data-testid={testId} style={{ marginBottom: 24 }}>
      <div style={{ color: '#9ca3af', fontSize: 13, marginBottom: 6, fontFamily: 'sans-serif' }}>{label}</div>
      <div className={stageBoxClass} style={stageBoxStyle}>
        <VideoPlayer
          videoRef={videoRef}
          videoUrl={SRC}
          handlers={NOOP_HANDLERS}
          fitToAspect={useAspectStage}
          zoom={ZOOM}
          panOffset={PAN_OFFSET}
          overlays={[
            <PlayerDetectionOverlay
              key="detections"
              videoRef={videoRef}
              videoMetadata={metadata}
              detections={DETECTIONS}
              detectionVideoWidth={REEL_META.width}
              detectionVideoHeight={REEL_META.height}
              zoom={ZOOM}
              panOffset={PAN_OFFSET}
            />,
          ]}
        />
      </div>
    </div>
  );
}

function T9100DiagHarness() {
  return (
    <div style={{ padding: 16, maxWidth: 1280, margin: '0 auto' }}>
      {STAGES.map((s) => (
        <DetectionStage key={s.testId} {...s} />
      ))}
    </div>
  );
}

createRoot(document.getElementById('t9100diag-root')).render(<T9100DiagHarness />);
