import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CollectionPlayer } from '../components/collections/CollectionPlayer';
import '../index.css'; // Tailwind — CollectionPlayer's fixed/inset/z classes need it

/**
 * T5860 — DEV-ONLY real-browser harness proving CollectionPlayer is modal.
 *
 * Mounts the REAL CollectionPlayer over a field of REAL interactive "tiles"
 * (buttons with hover + click handlers), mimicking the My Reels tiles/carousel
 * that sit behind the player. On desktop the panel's `md:inset-12` leaves a
 * ~48px gutter ring; the test drives a pointer into that gutter and asserts the
 * backdrop — not a tile — receives it (pre-fix: a tile did).
 *
 * The sample MP4 is generated by the Playwright spec's beforeAll via ffmpeg and
 * served at /collectionplayerdiag-sample.mp4 (not committed). NOT shipped:
 * Vite's default build entry is index.html only and collectionplayerdiag.html is
 * not added to rollupOptions.input, so it never enters the production bundle.
 *
 * T8540: also wired with onShare/onDownload (recorded into the SAME `status`
 * readout as hover/click) so the toolbar-primacy/ordering assertions can run
 * against the REAL Button component's real layout (jsdom never lays out
 * flex/DOM order the way a real browser paints it) without needing a logged-in
 * account or real reel data.
 */

const REELS = [
  { id: 1, name: 'Diag Reel', streamUrl: '/collectionplayerdiag-sample.mp4', aspect_ratio: '9:16', duration: null },
];

// A grid of tiles wide/tall enough that the desktop gutter point (x=8, y=mid)
// lands squarely on one — so pre-fix, elementFromPoint there is a tile button.
const TILES = Array.from({ length: 40 }, (_, i) => i);

function CollectionPlayerDiagHarness() {
  const [open, setOpen] = useState(true);
  const [lastHover, setLastHover] = useState('none');
  const [lastClick, setLastClick] = useState('none');

  return (
    <div style={{ minHeight: '100dvh', background: '#111827' }}>
      {/* Live status the spec reads to prove no tile interaction fired. */}
      <div
        data-testid="status"
        data-last-hover={lastHover}
        data-last-click={lastClick}
        style={{ position: 'fixed', top: 0, left: '50%', transform: 'translateX(-50%)', zIndex: 200, color: '#fff', fontSize: 12, padding: 4 }}
      >
        {`hover=${lastHover} click=${lastClick} open=${open}`}
      </div>

      {/* Background "My Reels" tiles — real hover/click handlers, full viewport. */}
      <div style={{ position: 'fixed', inset: 0, display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: 8, padding: 8 }}>
        {TILES.map((i) => (
          <button
            key={i}
            data-testid="bg-tile"
            data-tile-id={i}
            className="reel-tile"
            onMouseEnter={() => setLastHover(`tile-${i}`)}
            onClick={() => setLastClick(`tile-${i}`)}
            style={{ minHeight: 180, background: '#1f2937', color: '#9ca3af', border: '1px solid #374151', borderRadius: 8 }}
          >
            Tile {i}
          </button>
        ))}
      </div>

      {open && (
        <CollectionPlayer
          reels={REELS}
          title="Diag"
          onClose={() => setOpen(false)}
          onShare={() => setLastClick('share')}
          onDownload={() => setLastClick('download')}
        />
      )}
    </div>
  );
}

createRoot(document.getElementById('collectionplayerdiag-root')).render(<CollectionPlayerDiagHarness />);
