"""
T5630 — isolated unit tests for the NEW finalize primitives
(services/export_finalize.py), BEFORE they are wired into any caller.

- upsert_working_video: insert-once, resume-in-place (no duplicate version),
  project repoint, job completion, working_clips stamp.
- finalize_export: idempotent early-return, no-output_key guard, detect->persist
  ->sync happy path, detection fallback (_empty_video_detections, not None),
  and sync-failure staying at 'persisting'.

Uses the real profile DB (get_db_connection under a test user), mirroring the
T5600 harness, and monkeypatches the detection + sync externals.
"""

import uuid

import pytest

import app.routers.export.multi_clip as mc
import app.services.export_helpers as helpers
from app.database import get_db_connection
from app.profile_context import set_current_profile_id
from app.services import export_finalize as ef
from app.session_init import _init_cache
from app.user_context import set_current_user_id
from app.utils.encoding import decode_data, encode_data

TEST_USER_ID = f"test_t5630_unit_{uuid.uuid4().hex[:8]}"
TEST_PROFILE_ID = "testdefault"
_init_cache[TEST_USER_ID] = {"profile_id": TEST_PROFILE_ID, "is_new_user": False}

FAKE_REGIONS = [{"id": "r0", "label": "Clip A", "detections": [], "autoGenerated": True}]
FAKE_VIDEO_DETECTIONS = {"videoWidth": 810, "videoHeight": 1440, "fps": 30, "detections": []}


@pytest.fixture
def project():
    set_current_user_id(TEST_USER_ID)
    set_current_profile_id(TEST_PROFILE_ID)
    with get_db_connection() as conn:
        cur = conn.cursor()
        cur.execute("INSERT INTO projects (name, aspect_ratio) VALUES ('T5630 Unit', '9:16')")
        project_id = cur.lastrowid
        cur.execute(
            "INSERT INTO working_clips (project_id, uploaded_filename, version) VALUES (?, 'wc.mp4', 1)",
            (project_id,),
        )
        conn.commit()
    yield project_id
    with get_db_connection() as conn:
        cur = conn.cursor()
        cur.execute("UPDATE projects SET working_video_id = NULL WHERE id = ?", (project_id,))
        cur.execute("DELETE FROM working_videos WHERE project_id = ?", (project_id,))
        cur.execute("DELETE FROM working_clips WHERE project_id = ?", (project_id,))
        cur.execute("DELETE FROM export_jobs WHERE project_id = ?", (project_id,))
        cur.execute("DELETE FROM projects WHERE id = ?", (project_id,))
        conn.commit()


def _make_job(project_id, *, input_clips=None, stage="rendered", status="processing", output_video_id=None):
    export_id = f"exp-{uuid.uuid4().hex[:8]}"
    input_data = encode_data({"clips": input_clips or [{"clipIndex": 0, "duration": 5.0, "clipName": "Clip A"}],
                              "transition": {"type": "cut", "duration": 0}})
    with get_db_connection() as conn:
        conn.cursor().execute(
            "INSERT INTO export_jobs (id, project_id, type, status, input_data, stage, output_video_id) "
            "VALUES (?, ?, 'framing', ?, ?, ?, ?)",
            (export_id, project_id, status, input_data, stage, output_video_id),
        )
        conn.commit()
    return {
        "id": export_id,
        "project_id": project_id,
        "input_data": input_data,
        "stage": stage,
        "status": status,
        "output_video_id": output_video_id,
    }


# ---------------------------------------------------------------- upsert ----

def test_upsert_inserts_once_and_completes(project):
    job = _make_job(project)
    wv_id = ef.upsert_working_video(
        job, filename="working_x.mp4", duration=5.0,
        highlights_data=encode_data(FAKE_REGIONS), detections_data=encode_data(FAKE_VIDEO_DETECTIONS),
        gpu_seconds=2.0, modal_function="fn",
    )
    with get_db_connection() as conn:
        cur = conn.cursor()
        wv = cur.execute("SELECT id, version, duration, highlights_data, detections_data FROM working_videos WHERE id = ?", (wv_id,)).fetchone()
        proj_ptr = cur.execute("SELECT working_video_id FROM projects WHERE id = ?", (project,)).fetchone()[0]
        jr = cur.execute("SELECT status, output_video_id, output_filename, gpu_seconds, modal_function FROM export_jobs WHERE id = ?", (job["id"],)).fetchone()
        wc = cur.execute("SELECT exported_at FROM working_clips WHERE project_id = ?", (project,)).fetchone()[0]
    assert wv["version"] == 1
    assert decode_data(wv["highlights_data"]) == FAKE_REGIONS
    assert decode_data(wv["detections_data"]) == FAKE_VIDEO_DETECTIONS
    assert proj_ptr == wv_id
    assert jr["status"] == "complete" and jr["output_video_id"] == wv_id
    assert jr["output_filename"] == "working_x.mp4" and jr["gpu_seconds"] == 2.0 and jr["modal_function"] == "fn"
    assert wc is not None


def test_upsert_resume_updates_in_place_no_duplicate_version(project):
    """A job that already has output_video_id UPDATEs that row (same version),
    never inserts a second coexisting version."""
    job = _make_job(project)
    first = ef.upsert_working_video(job, filename="v1.mp4", duration=5.0,
                                    highlights_data=encode_data(FAKE_REGIONS), detections_data=None)
    # Simulate resume: the job now carries output_video_id.
    job["output_video_id"] = first
    second = ef.upsert_working_video(job, filename="v1b.mp4", duration=6.0,
                                     highlights_data=encode_data(FAKE_REGIONS), detections_data=encode_data(FAKE_VIDEO_DETECTIONS))
    assert second == first  # same row
    with get_db_connection() as conn:
        cur = conn.cursor()
        count = cur.execute("SELECT COUNT(*) c FROM working_videos WHERE project_id = ?", (project,)).fetchone()["c"]
        row = cur.execute("SELECT filename, duration, detections_data FROM working_videos WHERE id = ?", (first,)).fetchone()
    assert count == 1  # NO duplicate version
    assert row["filename"] == "v1b.mp4" and row["duration"] == 6.0
    assert decode_data(row["detections_data"]) == FAKE_VIDEO_DETECTIONS


def test_upsert_local_omits_detections_data(project):
    job = _make_job(project)
    wv_id = ef.upsert_working_video(job, filename="local.mp4", duration=5.0,
                                    highlights_data=encode_data(FAKE_REGIONS), detections_data=None)
    with get_db_connection() as conn:
        dd = conn.cursor().execute("SELECT detections_data FROM working_videos WHERE id = ?", (wv_id,)).fetchone()[0]
    assert dd is None


# ------------------------------------------------------------- finalize ----

def _patch_detect_and_sync(monkeypatch, detect_fn, sync_ok=True):
    monkeypatch.setattr(mc, "run_player_detection_for_highlights", detect_fn)
    monkeypatch.setattr(helpers, "sync_export_db_to_r2", lambda *a, **k: sync_ok)


@pytest.mark.asyncio
async def test_finalize_happy_path(project, monkeypatch):
    job = _make_job(project)

    async def fake_detect(**kwargs):
        return FAKE_REGIONS, FAKE_VIDEO_DETECTIONS

    _patch_detect_and_sync(monkeypatch, fake_detect)
    result = await ef.finalize_export(job, "working_videos/working_x.mp4", TEST_USER_ID, TEST_PROFILE_ID, video_duration=5.0)

    assert result["finalized"] is True and not result.get("sync_failed")
    with get_db_connection() as conn:
        cur = conn.cursor()
        wv = cur.execute("SELECT highlights_data, detections_data, duration FROM working_videos WHERE project_id = ?", (project,)).fetchone()
        jr = cur.execute("SELECT status, stage FROM export_jobs WHERE id = ?", (job["id"],)).fetchone()
    assert decode_data(wv["highlights_data"]) == FAKE_REGIONS
    assert decode_data(wv["detections_data"]) == FAKE_VIDEO_DETECTIONS
    assert wv["duration"] == 5.0
    assert jr["status"] == "complete" and jr["stage"] == "complete"


@pytest.mark.asyncio
async def test_finalize_idempotent_when_already_complete(project, monkeypatch):
    job = _make_job(project, stage="complete", status="complete", output_video_id=777)

    async def boom(**kwargs):
        raise AssertionError("detection must not run for a complete job")

    _patch_detect_and_sync(monkeypatch, boom)
    result = await ef.finalize_export(job, "working_videos/working_x.mp4", TEST_USER_ID, TEST_PROFILE_ID)
    assert result["already_finalized"] is True and result["working_video_id"] == 777
    with get_db_connection() as conn:
        count = conn.cursor().execute("SELECT COUNT(*) c FROM working_videos WHERE project_id = ?", (project,)).fetchone()["c"]
    assert count == 0  # no new row


@pytest.mark.asyncio
async def test_finalize_no_output_key_fails_loudly(project, monkeypatch):
    job = _make_job(project)

    async def fake_detect(**kwargs):
        return FAKE_REGIONS, FAKE_VIDEO_DETECTIONS

    _patch_detect_and_sync(monkeypatch, fake_detect)
    result = await ef.finalize_export(job, "", TEST_USER_ID, TEST_PROFILE_ID)
    assert result["finalized"] is False and "output_key" in result["error"]
    with get_db_connection() as conn:
        cur = conn.cursor()
        count = cur.execute("SELECT COUNT(*) c FROM working_videos WHERE project_id = ?", (project,)).fetchone()["c"]
        status = cur.execute("SELECT status FROM export_jobs WHERE id = ?", (job["id"],)).fetchone()[0]
    assert count == 0 and status == "error"


@pytest.mark.asyncio
async def test_finalize_detection_fallback_writes_empty_detections(project, monkeypatch):
    job = _make_job(project)

    async def fake_detect_raises(**kwargs):
        raise RuntimeError("detection boom")

    _patch_detect_and_sync(monkeypatch, fake_detect_raises)
    result = await ef.finalize_export(job, "working_videos/working_x.mp4", TEST_USER_ID, TEST_PROFILE_ID)
    assert result["finalized"] is True
    with get_db_connection() as conn:
        wv = conn.cursor().execute("SELECT highlights_data, detections_data FROM working_videos WHERE project_id = ?", (project,)).fetchone()
    # default region generated; empty-detections blob (NOT NULL)
    assert decode_data(wv["highlights_data"])  # non-empty list of default regions
    assert wv["detections_data"] is not None
    assert decode_data(wv["detections_data"])["detections"] == []


@pytest.mark.asyncio
async def test_finalize_sync_failure_stays_persisting(project, monkeypatch):
    job = _make_job(project)

    async def fake_detect(**kwargs):
        return FAKE_REGIONS, FAKE_VIDEO_DETECTIONS

    _patch_detect_and_sync(monkeypatch, fake_detect, sync_ok=False)
    result = await ef.finalize_export(job, "working_videos/working_x.mp4", TEST_USER_ID, TEST_PROFILE_ID)
    assert result["sync_failed"] is True and result["finalized"] is True
    with get_db_connection() as conn:
        stage = conn.cursor().execute("SELECT stage FROM export_jobs WHERE id = ?", (job["id"],)).fetchone()[0]
    # working_video is persisted locally but we did NOT advance to 'complete'.
    assert stage == "persisting"
