"""
T5630 CHARACTERIZATION tests — pin the CURRENT complete-path DB deltas of the
multi-clip finalizer BEFORE the staged/unified-finalize refactor, so the happy
path cannot drift while writers 1/2/3 are consolidated (export-pipeline.md:
"no characterization safety net over this pipeline").

Three scenarios, each asserting the exact rows a finalize produces today:
  (a) local in-band  (`_export_clips` local branch, writer 2)
  (b) Modal in-band  (`_export_clips` Modal branch, writer 1)
  (c) recovery       (`finalize_modal_export`, writer 3 — the BUGGY minimal row)

(a) and (b) MUST stay green through every strangler-fig step (the whole point).
(c) pins the current bug (empty highlights) and is INTENTIONALLY flipped to the
fixed behavior in the recovery-flip commit — see the companion assertion there.

Modal harness mirrors test_t5600 (mock the Modal AI call, R2, detection, sync).
Local harness mocks the heavy ffmpeg/upscale/upload/detection so the local
branch reaches its DB-save block with deterministic inputs.
"""

import uuid

import pytest

import app.routers.export.multi_clip as mc
import app.routers.exports as exports_router
import app.services.export_helpers as helpers
from app.database import get_db_connection
from app.profile_context import set_current_profile_id
from app.session_init import _init_cache
from app.user_context import set_current_user_id
from app.utils.encoding import decode_data

TEST_USER_ID = f"test_t5630_char_{uuid.uuid4().hex[:8]}"
TEST_PROFILE_ID = "testdefault"
_init_cache[TEST_USER_ID] = {"profile_id": TEST_PROFILE_ID, "is_new_user": False}

FAKE_REGIONS = [
    {
        "id": "region-auto-0",
        "start_time": 0.0,
        "end_time": 2.0,
        "enabled": True,
        "label": "Clip A",
        "autoGenerated": True,
        "keyframes": [],
        "detections": [{"timestamp": 0.5, "frame": 15, "boxes": [{"x": 0.1, "y": 0.1}]}],
        "videoWidth": 810,
        "videoHeight": 1440,
        "fps": 30,
    }
]
FAKE_VIDEO_DETECTIONS = {
    "videoWidth": 810,
    "videoHeight": 1440,
    "fps": 30,
    "detections": [{"timestamp": 0.5, "frame": 15, "boxes": [{"x": 0.1, "y": 0.1}]}],
}


def _make_clip():
    return mc.ClipExportData(
        clip_index=0,
        crop_keyframes=[],
        segments=[],
        duration=5.0,
        video_file=mc.BytesFile(b"fake-mp4"),
        source_fps=30.0,
        clip_name="Clip A",
    )


@pytest.fixture
def project():
    """A project with ONE working_clip (so exported_at stamping is observable)."""
    set_current_user_id(TEST_USER_ID)
    set_current_profile_id(TEST_PROFILE_ID)
    with get_db_connection() as conn:
        cur = conn.cursor()
        cur.execute("INSERT INTO projects (name, aspect_ratio) VALUES ('T5630 Char', '9:16')")
        project_id = cur.lastrowid
        cur.execute(
            "INSERT INTO working_clips (project_id, uploaded_filename, version) VALUES (?, 'wc.mp4', 1)",
            (project_id,),
        )
        conn.commit()
    yield project_id
    with get_db_connection() as conn:
        cur = conn.cursor()
        cur.execute("UPDATE projects SET working_video_id = NULL WHERE id = ?", (project_id,))
        cur.execute("DELETE FROM working_videos WHERE project_id = ?", (project_id,))
        cur.execute("DELETE FROM working_clips WHERE project_id = ?", (project_id,))
        cur.execute("DELETE FROM export_jobs WHERE project_id = ?", (project_id,))
        cur.execute("DELETE FROM projects WHERE id = ?", (project_id,))
        conn.commit()


def _create_job(export_id, project_id):
    with get_db_connection() as conn:
        conn.cursor().execute(
            "INSERT INTO export_jobs (id, project_id, type, status, input_data) "
            "VALUES (?, ?, 'framing', 'processing', '{}')",
            (export_id, project_id),
        )
        conn.commit()


# ============================================================================
# (b) Modal in-band — writer 1 (COMPLETE)
# ============================================================================

def _patch_modal(monkeypatch, detect_fn):
    async def fake_send_progress(export_id, data):
        return None

    async def fake_modal(**kwargs):
        return {"status": "success", "gpu_seconds": 1.0, "modal_function": "test", "clips_processed": 1}

    async def fake_delete(*a, **k):
        return True

    monkeypatch.setattr(mc, "modal_enabled", lambda: True)
    monkeypatch.setattr(mc.manager, "send_progress", fake_send_progress)
    monkeypatch.setattr(mc, "upload_bytes_to_r2", lambda *a, **k: True)
    monkeypatch.setattr(mc, "call_modal_clips_ai", fake_modal)
    monkeypatch.setattr(mc, "delete_from_r2", fake_delete)
    monkeypatch.setattr(mc, "download_from_r2", lambda *a, **k: False)
    monkeypatch.setattr(mc, "run_player_detection_for_highlights", detect_fn)
    monkeypatch.setattr(mc, "generate_presigned_url", lambda *a, **k: "https://r2/fake")
    monkeypatch.setattr(helpers, "sync_export_db_to_r2", lambda *a, **k: True)


async def _run_modal(export_id, project_id):
    set_current_user_id(TEST_USER_ID)
    set_current_profile_id(TEST_PROFILE_ID)
    return await mc._export_clips(
        export_id=export_id,
        clips=[_make_clip()],
        aspect_ratio="9:16",
        transition={"type": "cut", "duration": 0},
        include_audio=False,
        target_fps=30,
        export_mode="standard",
        project_id=project_id,
        project_name="T5630 Char Reel",
        user_id=TEST_USER_ID,
        profile_id=TEST_PROFILE_ID,
        credits_deducted=0,
        total_video_seconds=5.0,
    )


@pytest.mark.asyncio
async def test_char_modal_inband_complete(project, monkeypatch):
    export_id = f"exp-{uuid.uuid4().hex[:8]}"
    _create_job(export_id, project)

    async def fake_detect(**kwargs):
        return FAKE_REGIONS, FAKE_VIDEO_DETECTIONS

    _patch_modal(monkeypatch, fake_detect)
    await _run_modal(export_id, project)

    with get_db_connection() as conn:
        cur = conn.cursor()
        wv = cur.execute(
            "SELECT id, filename, version, highlights_data, detections_data FROM working_videos WHERE project_id = ?",
            (project,),
        ).fetchone()
        proj_ptr = cur.execute("SELECT working_video_id FROM projects WHERE id = ?", (project,)).fetchone()[0]
        job = cur.execute(
            "SELECT status, output_video_id, output_filename, gpu_seconds, modal_function FROM export_jobs WHERE id = ?",
            (export_id,),
        ).fetchone()
        wc_exported = cur.execute(
            "SELECT exported_at FROM working_clips WHERE project_id = ?", (project,)
        ).fetchone()[0]

    # working_videos row: highlights + detections both populated (COMPLETE)
    assert wv is not None
    assert decode_data(wv["highlights_data"]) == FAKE_REGIONS
    assert decode_data(wv["detections_data"]) == FAKE_VIDEO_DETECTIONS
    # project repointed at the new working video
    assert proj_ptr == wv["id"]
    # job completed with output refs + gpu metadata
    assert job["status"] == "complete"
    assert job["output_video_id"] == wv["id"]
    assert job["output_filename"] == wv["filename"]
    assert job["gpu_seconds"] == 1.0
    assert job["modal_function"] == "test"
    # working_clips.exported_at stamped
    assert wc_exported is not None


@pytest.mark.asyncio
async def test_char_modal_inband_detection_fallback(project, monkeypatch):
    """Detection raises -> fallback writes default regions + EMPTY detections
    (NOT null). Pins BINDING fidelity rule #2 (_empty_video_detections)."""
    export_id = f"exp-{uuid.uuid4().hex[:8]}"
    _create_job(export_id, project)

    async def fake_detect_raises(**kwargs):
        raise RuntimeError("detection boom")

    _patch_modal(monkeypatch, fake_detect_raises)
    await _run_modal(export_id, project)

    with get_db_connection() as conn:
        wv = conn.cursor().execute(
            "SELECT highlights_data, detections_data FROM working_videos WHERE project_id = ?",
            (project,),
        ).fetchone()

    # default regions generated from the single source clip
    regions = decode_data(wv["highlights_data"])
    assert isinstance(regions, list) and len(regions) == 1
    assert regions[0]["autoGenerated"] is True
    # empty-detections blob, NOT NULL
    assert wv["detections_data"] is not None
    assert decode_data(wv["detections_data"])["detections"] == []


# ============================================================================
# (a) local in-band — writer 2 (COMPLETE-ish; detections_data omitted)
# ============================================================================

def _patch_local(monkeypatch, detect_fn):
    async def fake_send_progress(export_id, data):
        return None

    async def fake_process_single_clip(**kwargs):
        return "/tmp/fake_processed.mp4"

    def fake_concat(**kwargs):
        return None

    monkeypatch.setattr(mc, "modal_enabled", lambda: False)
    monkeypatch.setattr(mc.manager, "send_progress", fake_send_progress)
    monkeypatch.setattr(mc, "process_single_clip", fake_process_single_clip)
    monkeypatch.setattr(mc, "concatenate_clips_with_transition", fake_concat)
    monkeypatch.setattr(mc, "get_video_duration", lambda *a, **k: 5.0)
    monkeypatch.setattr(mc, "upload_to_r2", lambda *a, **k: True)
    monkeypatch.setattr(mc, "run_local_detection_on_video_file", detect_fn)
    monkeypatch.setattr(helpers, "sync_export_db_to_r2", lambda *a, **k: True)


async def _run_local(export_id, project_id):
    set_current_user_id(TEST_USER_ID)
    set_current_profile_id(TEST_PROFILE_ID)
    return await mc._export_clips(
        export_id=export_id,
        clips=[_make_clip()],
        aspect_ratio="9:16",
        transition={"type": "cut", "duration": 0},
        include_audio=False,
        target_fps=30,
        export_mode="standard",
        project_id=project_id,
        project_name="T5630 Char Reel",
        user_id=TEST_USER_ID,
        profile_id=TEST_PROFILE_ID,
        credits_deducted=0,
        total_video_seconds=5.0,
        is_test_mode=True,
    )


@pytest.mark.asyncio
async def test_char_local_inband_complete(project, monkeypatch):
    export_id = f"exp-{uuid.uuid4().hex[:8]}"
    _create_job(export_id, project)

    async def fake_detect(**kwargs):
        return FAKE_REGIONS

    _patch_local(monkeypatch, fake_detect)
    await _run_local(export_id, project)

    with get_db_connection() as conn:
        cur = conn.cursor()
        wv = cur.execute(
            "SELECT id, filename, version, duration, highlights_data, detections_data FROM working_videos WHERE project_id = ?",
            (project,),
        ).fetchone()
        proj_ptr = cur.execute("SELECT working_video_id FROM projects WHERE id = ?", (project,)).fetchone()[0]
        job = cur.execute("SELECT status, output_video_id FROM export_jobs WHERE id = ?", (export_id,)).fetchone()
        wc_exported = cur.execute(
            "SELECT exported_at FROM working_clips WHERE project_id = ?", (project,)
        ).fetchone()[0]

    assert wv is not None
    assert decode_data(wv["highlights_data"]) == FAKE_REGIONS
    # writer 2 OMITS detections_data (regions carry embedded detections) -> NULL
    assert wv["detections_data"] is None
    assert wv["duration"] == 5.0
    assert proj_ptr == wv["id"]
    assert job["status"] == "complete"
    assert job["output_video_id"] == wv["id"]
    assert wc_exported is not None


# ============================================================================
# (c) recovery — writer 3 CURRENT BUGGY minimal row (flipped in recovery commit)
# ============================================================================

@pytest.mark.asyncio
async def test_char_recovery_current_minimal_row(project, monkeypatch):
    """CURRENT behavior: finalize_modal_export writes a minimal working_videos
    row (filename only) — NO highlights_data, NO detections_data, NO duration.
    This is the Brilliant-Control bug; the recovery-flip commit REPLACES this
    assertion with the fixed (populated-highlights) expectation."""
    export_id = f"exp-{uuid.uuid4().hex[:8]}"
    _create_job(export_id, project)
    monkeypatch.setattr(exports_router, "record_milestone", lambda *a, **k: None)

    job = exports_router.get_export_job(export_id)
    result = exports_router.finalize_modal_export(
        job=job,
        modal_result={"output_key": "working_videos/working_rec_abc.mp4"},
        user_id=TEST_USER_ID,
    )

    assert result["finalized"] is True
    with get_db_connection() as conn:
        cur = conn.cursor()
        wv = cur.execute(
            "SELECT filename, highlights_data, detections_data, duration FROM working_videos WHERE project_id = ?",
            (project,),
        ).fetchone()
        proj_ptr = cur.execute("SELECT working_video_id FROM projects WHERE id = ?", (project,)).fetchone()[0]
        job_row = cur.execute("SELECT status, output_filename FROM export_jobs WHERE id = ?", (export_id,)).fetchone()

    assert wv["filename"] == "working_rec_abc.mp4"
    # THE BUG: recovery produced NO overlay data.
    assert wv["highlights_data"] is None
    assert wv["detections_data"] is None
    assert wv["duration"] is None
    assert proj_ptr is not None
    assert job_row["status"] == "complete"
    assert job_row["output_filename"] == "working_rec_abc.mp4"
