"""
T5600 — multi-clip export persists working_videos.detections_data.

`run_player_detection_for_highlights` now returns (regions, video_detections)
instead of just regions; `_export_clips`'s Modal branch unpacks the tuple and
writes `video_detections` into the new `detections_data` column at INSERT time
(multi_clip.py, additive alongside the existing `highlights_data` write).

Reuses the T4200 durability harness (same mocked externals: Modal AI call, R2
upload/delete, progress websocket) with the detection fake replaced by one
that returns REAL regions + a real video-level payload, so the assertion is on
the actual encoded column, not just "the call didn't crash".
"""

import uuid

import pytest

import app.routers.export.multi_clip as mc
import app.services.export_helpers as helpers
from app.database import get_db_connection
from app.profile_context import set_current_profile_id
from app.session_init import _init_cache
from app.user_context import set_current_user_id
from app.utils.encoding import decode_data

TEST_USER_ID = f"test_t5600_export_{uuid.uuid4().hex[:8]}"
TEST_PROFILE_ID = "testdefault"
_init_cache[TEST_USER_ID] = {"profile_id": TEST_PROFILE_ID, "is_new_user": False}

FAKE_REGIONS = [
    {
        "id": "region-auto-0",
        "start_time": 0.0,
        "end_time": 2.0,
        "enabled": True,
        "label": "Clip A",
        "autoGenerated": True,
        "keyframes": [],
        "detections": [{"timestamp": 0.5, "frame": 15, "boxes": [{"x": 0.1, "y": 0.1}]}],
        "videoWidth": 810,
        "videoHeight": 1440,
        "fps": 30,
    }
]
FAKE_VIDEO_DETECTIONS = {
    "videoWidth": 810,
    "videoHeight": 1440,
    "fps": 30,
    "detections": [{"timestamp": 0.5, "frame": 15, "boxes": [{"x": 0.1, "y": 0.1}]}],
}


def _make_clip():
    return mc.ClipExportData(
        clip_index=0,
        crop_keyframes=[],
        segments=[],
        duration=5.0,
        video_file=mc.BytesFile(b"fake-mp4"),
        source_fps=30.0,
        clip_name="Clip A",
    )


@pytest.fixture
def project():
    set_current_user_id(TEST_USER_ID)
    set_current_profile_id(TEST_PROFILE_ID)
    with get_db_connection() as conn:
        cur = conn.cursor()
        cur.execute("INSERT INTO projects (name, aspect_ratio) VALUES ('T5600 Export', '9:16')")
        project_id = cur.lastrowid
        conn.commit()
    yield project_id
    with get_db_connection() as conn:
        cur = conn.cursor()
        cur.execute("UPDATE projects SET working_video_id = NULL WHERE id = ?", (project_id,))
        cur.execute("DELETE FROM working_videos WHERE project_id = ?", (project_id,))
        cur.execute("DELETE FROM projects WHERE id = ?", (project_id,))
        conn.commit()


def _patch_modal_pipeline(monkeypatch, sent, detect_fn):
    async def fake_send_progress(export_id, data):
        sent.append(data)

    async def fake_modal(**kwargs):
        return {"status": "success", "gpu_seconds": 1.0, "modal_function": "test", "clips_processed": 1}

    async def fake_delete(*a, **k):
        return True

    monkeypatch.setattr(mc, "modal_enabled", lambda: True)
    monkeypatch.setattr(mc.manager, "send_progress", fake_send_progress)
    monkeypatch.setattr(mc, "upload_bytes_to_r2", lambda *a, **k: True)
    monkeypatch.setattr(mc, "call_modal_clips_ai", fake_modal)
    monkeypatch.setattr(mc, "delete_from_r2", fake_delete)
    monkeypatch.setattr(mc, "download_from_r2", lambda *a, **k: False)
    monkeypatch.setattr(mc, "run_player_detection_for_highlights", detect_fn)
    monkeypatch.setattr(helpers, "sync_export_db_to_r2", lambda *a, **k: True)


async def _run(project_id):
    set_current_user_id(TEST_USER_ID)
    set_current_profile_id(TEST_PROFILE_ID)
    return await mc._export_clips(
        export_id=f"exp-{uuid.uuid4().hex[:6]}",
        clips=[_make_clip()],
        aspect_ratio="9:16",
        transition={"type": "cut", "duration": 0},
        include_audio=False,
        target_fps=30,
        export_mode="standard",
        project_id=project_id,
        project_name="T5600 Export Reel",
        user_id=TEST_USER_ID,
        profile_id=TEST_PROFILE_ID,
        credits_deducted=0,
        total_video_seconds=5.0,
    )


@pytest.mark.asyncio
async def test_export_writes_detections_data_column(project, monkeypatch):
    async def fake_detect(**kwargs):
        return FAKE_REGIONS, FAKE_VIDEO_DETECTIONS

    sent = []
    _patch_modal_pipeline(monkeypatch, sent, fake_detect)

    await _run(project)

    with get_db_connection() as conn:
        row = conn.cursor().execute(
            "SELECT wv.detections_data, wv.highlights_data FROM working_videos wv "
            "JOIN projects p ON p.working_video_id = wv.id WHERE p.id = ?",
            (project,),
        ).fetchone()

    assert row["detections_data"] is not None
    payload = decode_data(row["detections_data"])
    assert payload == FAKE_VIDEO_DETECTIONS

    # Additive: highlights_data still carries the (now-legacy) per-region copy.
    regions = decode_data(row["highlights_data"])
    assert regions[0]["detections"] == FAKE_REGIONS[0]["detections"]


@pytest.mark.asyncio
async def test_export_fallback_path_writes_empty_detections_data(project, monkeypatch):
    """When detection raises, the except-branch fallback must still write a
    (empty) detections_data -- never leave the INSERT referencing an undefined
    local (the tuple-unpack landmine this task's producer-signature change
    could otherwise introduce)."""
    async def fake_detect_raises(**kwargs):
        raise RuntimeError("simulated detection failure")

    sent = []
    _patch_modal_pipeline(monkeypatch, sent, fake_detect_raises)

    await _run(project)

    with get_db_connection() as conn:
        row = conn.cursor().execute(
            "SELECT wv.detections_data FROM working_videos wv "
            "JOIN projects p ON p.working_video_id = wv.id WHERE p.id = ?",
            (project,),
        ).fetchone()

    assert row["detections_data"] is not None
    payload = decode_data(row["detections_data"])
    assert payload["detections"] == []
