import React, { useState, useEffect, useCallback } from 'react';
import { Trash2, Star, Check } from 'lucide-react';
import { soccerTags, positions, generateClipName } from '../constants/soccerTags';
import ClipScrubRegion from './ClipScrubRegion';

// Rating-based background colors (used for tinting the details panel)
const RATING_COLORS = {
  5: 'rgba(234, 179, 8, 0.15)',   // gold/yellow
  4: 'rgba(34, 197, 94, 0.15)',   // green
  3: 'rgba(59, 130, 246, 0.15)',  // blue
  2: 'rgba(249, 115, 22, 0.15)',  // orange
  1: 'rgba(239, 68, 68, 0.15)',   // red
};

// Rating-based border colors
const RATING_BORDER_COLORS = {
  5: '#eab308', // gold/yellow
  4: '#22c55e', // green
  3: '#3b82f6', // blue
  2: '#f97316', // orange
  1: '#ef4444', // red
};

/**
 * StarRating - 5-star rating selector
 */
function StarRating({ rating, onRatingChange }) {
  return (
    <div className="flex items-center gap-0.5">
      {[1, 2, 3, 4, 5].map((starNum) => (
        <button
          key={starNum}
          onClick={() => onRatingChange(starNum)}
          className="p-0.5 hover:scale-110 transition-transform"
          title={`${starNum} star${starNum > 1 ? 's' : ''}`}
        >
          <Star
            size={18}
            fill={starNum <= rating ? '#fbbf24' : 'transparent'}
            color={starNum <= rating ? '#fbbf24' : '#6b7280'}
            strokeWidth={1.5}
          />
        </button>
      ))}
    </div>
  );
}

/**
 * TagSelector - Multi-select tags grouped by position
 * Shows all tags from all positions, allowing selection from multiple positions
 */
function TagSelector({ selectedTags, onTagToggle, compact = false }) {
  return (
    <div className={compact ? 'space-y-1.5' : 'space-y-2'}>
      {positions.map((pos) => {
        const positionTags = soccerTags[pos.id] || [];
        return (
          <div key={pos.id}>
            {/* Position groups rendered without labels */}
            <div className={`flex flex-wrap gap-1`}>
              {positionTags.map((tag) => {
                const isSelected = selectedTags.includes(tag.name);
                return (
                  <button
                    key={tag.name}
                    onClick={() => onTagToggle(tag.name)}
                    className={`flex items-center gap-1 rounded transition-colors ${
                      compact ? 'px-1.5 py-1 text-[11px]' : 'px-2 py-1 text-xs'
                    } ${
                      isSelected
                        ? 'bg-green-600 text-white'
                        : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
                    }`}
                    title={tag.description}
                  >
                    {isSelected && <Check size={compact ? 10 : 12} />}
                    {tag.name}
                  </button>
                );
              })}
            </div>
          </div>
        );
      })}
    </div>
  );
}

/**
 * ClipDetailsEditor - Edit panel for selected clip details
 *
 * Editable fields:
 * - Star rating (1-5)
 * - Name
 * - End time (editable - this is where playhead was when clip was created)
 * - Duration (slider)
 * - Notes
 *
 * Read-only:
 * - Start time (calculated from end - duration)
 */
export function ClipDetailsEditor({
  region,
  onUpdate,
  onDelete,
  maxNotesLength = 280,
  videoDuration,
  onSeek,
  videoRef,
  onScrubLock,
  onScrubUnlock,
}) {
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  // Local scrub state — same pattern as AnnotateFullscreenOverlay.
  // Dragging updates local state instantly; persisted to parent on change.
  const [scrubStartTime, setScrubStartTime] = useState(region.startTime);
  const [scrubEndTime, setScrubEndTime] = useState(region.endTime);

  // Sync local state only when switching to a different clip.
  // Do NOT sync on region.startTime/endTime changes — during drag, local state
  // is authoritative and the parent round-trip would fight with it.
  useEffect(() => {
    setScrubStartTime(region.startTime);
    setScrubEndTime(region.endTime);
  }, [region.id]); // eslint-disable-line react-hooks/exhaustive-deps

  const notesLength = region.notes?.length || 0;

  // Derive display name from region.name or auto-generate from rating+tags
  const displayName = region.name || generateClipName(region.rating || 3, region.tags || [], region.notes || '') || '';
  const isAutoGenerated = !region.name && (region.tags?.length > 0 || region.notes?.trim());

  const handleNameChange = (e) => {
    // Store whatever the user types - empty string means "use auto-generated"
    onUpdate({ name: e.target.value });
  };

  const handleRatingChange = (newRating) => {
    // Only update rating, don't touch the name
    onUpdate({ rating: newRating });
  };

  const handleTagToggle = (tagName) => {
    const currentTags = region.tags || [];
    const newTags = currentTags.includes(tagName)
      ? currentTags.filter((t) => t !== tagName)
      : [...currentTags, tagName];

    // Only update tags, don't touch the name
    onUpdate({ tags: newTags });
  };

  // During drag: only update local state (instant, no parent re-render)
  const handleStartTimeChange = useCallback((newStart) => {
    setScrubStartTime(newStart);
  }, []);

  const handleEndTimeChange = useCallback((newEnd) => {
    setScrubEndTime(newEnd);
  }, []);

  // Lock auto-deselect while scrubbing so onSeek doesn't close the sidebar
  const handleDragStart = useCallback(() => {
    onScrubLock?.();
  }, [onScrubLock]);

  // On drag end: persist, unlock auto-deselect, seek to new start so
  // currentTime is within the updated clip range
  const handleDragEnd = useCallback((finalStart, finalEnd) => {
    onScrubUnlock?.();
    onUpdate({ startTime: finalStart, endTime: finalEnd });
    onSeek?.(finalStart);
  }, [onScrubUnlock, onUpdate, onSeek]);

  const handleNotesChange = (e) => {
    const newNotes = e.target.value.slice(0, maxNotesLength);
    onUpdate({ notes: newNotes });
  };

  const handleDeleteClick = () => {
    setShowDeleteConfirm(true);
  };

  const handleConfirmDelete = () => {
    setShowDeleteConfirm(false);
    onDelete();
  };

  const handleCancelDelete = () => {
    setShowDeleteConfirm(false);
  };

  const rating = region.rating || 3;
  const ratingColor = RATING_COLORS[rating] || RATING_COLORS[3];
  const ratingBorderColor = RATING_BORDER_COLORS[rating] || RATING_BORDER_COLORS[3];

  return (
    <div
      className="border-t-2"
      style={{
        backgroundColor: ratingColor,
        borderTopColor: ratingBorderColor,
      }}
    >
      <div className="p-3 space-y-3">
        {/* Header */}
        <div className="text-gray-400 text-xs uppercase tracking-wider">
          Clip Details
        </div>

        {/* Clip scrub region — same visual timeline used in the Add/Edit overlay.
            onScrubLock/onScrubUnlock suppress auto-deselect during drag so that
            onSeek can preview frames without closing the sidebar. */}
        <ClipScrubRegion
          currentTime={region.startTime + (region.endTime - region.startTime) / 2}
          videoDuration={videoDuration}
          existingClip={region}
          startTime={scrubStartTime}
          endTime={scrubEndTime}
          onStartTimeChange={handleStartTimeChange}
          onEndTimeChange={handleEndTimeChange}
          onDragStart={handleDragStart}
          onDragEnd={handleDragEnd}
          onSeek={onSeek}
          videoRef={videoRef}
        />

        {/* Star Rating */}
        <div className="flex items-center gap-2">
          <label className="text-gray-400 text-xs w-16 shrink-0">Rating</label>
          <StarRating
            rating={region.rating || 3}
            onRatingChange={handleRatingChange}
          />
        </div>

        {/* Tags Selection */}
        <div>
          <label className="block text-gray-400 text-xs mb-1">Tags</label>
          <TagSelector
            selectedTags={region.tags || []}
            onTagToggle={handleTagToggle}
          />
        </div>

        {/* Name Input */}
        <div className="flex items-center gap-2">
          <label className="text-gray-400 text-xs w-16 shrink-0">
            Name
            {isAutoGenerated && <span className="text-gray-500 ml-1">(auto)</span>}
          </label>
          <input
            type="text"
            value={displayName}
            onChange={handleNameChange}
            className="flex-1 px-2 py-1.5 bg-gray-700 border border-gray-600 rounded text-white text-sm focus:outline-none focus:border-blue-500"
            placeholder="Clip name"
          />
        </div>

        {/* Notes Textarea */}
        <div>
          <div className="flex justify-between items-center mb-1">
            <label className="text-gray-400 text-xs">Notes</label>
            <span className={`text-xs ${notesLength >= maxNotesLength ? 'text-red-400' : 'text-gray-500'}`}>
              {notesLength}/{maxNotesLength}
            </span>
          </div>
          <textarea
            value={region.notes || ''}
            onChange={handleNotesChange}
            className="w-full px-2 py-1.5 bg-gray-700 border border-gray-600 rounded text-white text-sm focus:outline-none focus:border-blue-500 resize-none"
            placeholder="Add notes (shown as overlay during playback)"
            rows={3}
          />
        </div>

        {/* Delete Button */}
        {showDeleteConfirm ? (
          <div className="flex gap-2">
            <button
              onClick={handleConfirmDelete}
              className="flex-1 px-3 py-1.5 bg-red-600 hover:bg-red-700 text-white rounded text-sm transition-colors"
            >
              Confirm Delete
            </button>
            <button
              onClick={handleCancelDelete}
              className="flex-1 px-3 py-1.5 bg-gray-600 hover:bg-gray-500 text-white rounded text-sm transition-colors"
            >
              Cancel
            </button>
          </div>
        ) : (
          <button
            onClick={handleDeleteClick}
            className="w-full px-3 py-1.5 bg-gray-700 hover:bg-red-600 text-gray-300 hover:text-white rounded text-sm flex items-center justify-center gap-1.5 transition-colors"
          >
            <Trash2 className="w-4 h-4" />
            <span>Delete Clip</span>
          </button>
        )}
      </div>
    </div>
  );
}

export default ClipDetailsEditor;
