import { useRef, useState, useCallback, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
// eslint-disable-next-line no-unused-vars -- rendered as JSX below; repo eslint lacks react/jsx-uses-vars
import HighlightOverlay from '../modes/overlay/overlays/HighlightOverlay';
// eslint-disable-next-line no-unused-vars -- rendered as JSX below; repo eslint lacks react/jsx-uses-vars
import OverrideHint from '../modes/overlay/overlays/OverrideHint';
import '../index.css'; // Tailwind — the hint pill + handle classes need it

/**
 * T5610 — DEV-ONLY real-browser harness for "tap the spotlight to edit" + the hint.
 *
 * Mounts the REAL HighlightOverlay + REAL OverrideHint against a REAL <video>, and
 * replicates OverlayModeView's T5610 glue EXACTLY (the trivial view-state wiring the
 * parent owns; the risky pointer/hit-testing is the real component):
 *   - editable = !showPlayerBoxes || circleEditActive
 *   - onCircleTap wired only while tracking is on (showPlayerBoxes)
 *   - the video-container tap-nav YIELDS while editable and exits circle-edit on an
 *     OUTSIDE tap (handleVideoAreaTap)
 *   - exit circle-edit on play; mark the hint learned on first override
 *
 * jsdom is insufficient here (T5390/T5570 lesson: pointer hit-testing on real touch).
 * A real 640x360 sample MP4 is served at /overlaydiag-sample.mp4 (generated by the
 * Playwright spec's beforeAll via ffmpeg; not committed). overlaydiag-t5610.html is not
 * a vite build input, so this never enters the production bundle.
 */

const VIDEO_METADATA = { width: 640, height: 360, duration: 3, framerate: 30 };
// Stable references: passing fresh {x,y} / new objects each render would retrigger
// useVideoDisplayRect's layout effect in a loop (mirrors how OverlayModeView passes
// stable zoom/panOffset from props).
const ZOOM = 1;
const PAN_OFFSET = { x: 0, y: 0 };
const INITIAL_HIGHLIGHT = {
  x: 320, y: 180, radiusX: 50, radiusY: 80,
  strokeOpacity: 0.85, fillOpacity: 0.05, color: '#FFD400',
};

// eslint-disable-next-line no-unused-vars -- rendered as JSX at the bottom; repo eslint lacks react/jsx-uses-vars
function OverrideDiagHarness() {
  const videoRef = useRef(null);
  const [highlight, setHighlight] = useState(INITIAL_HIGHLIGHT);
  const [showPlayerBoxes, setShowPlayerBoxes] = useState(true); // tracking ON by default
  const [circleEditActive, setCircleEditActive] = useState(false);
  const [overrideUsed, setOverrideUsed] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);

  useEffect(() => {
    const v = videoRef.current;
    if (!v) return undefined;
    const onTime = () => setCurrentTime(v.currentTime);
    const onPlay = () => setIsPlaying(true);
    const onPause = () => setIsPlaying(false);
    v.addEventListener('timeupdate', onTime);
    v.addEventListener('play', onPlay);
    v.addEventListener('pause', onPause);
    return () => {
      v.removeEventListener('timeupdate', onTime);
      v.removeEventListener('play', onPlay);
      v.removeEventListener('pause', onPause);
    };
  }, []);

  // ---- OverlayModeView T5610 glue (mirrored) ----
  const editable = !showPlayerBoxes || circleEditActive;
  const hasVisibleSpotlight = true; // region is always active in this harness
  const showOverrideHint = hasVisibleSpotlight && showPlayerBoxes && !overrideUsed;
  const overrideHintText = 'Tap the spotlight to adjust it — or hide tracking to edit freely';

  const handleCircleTap = useCallback(() => setCircleEditActive((v) => !v), []);

  useEffect(() => {
    if (circleEditActive || !showPlayerBoxes) setOverrideUsed(true);
  }, [circleEditActive, showPlayerBoxes]);
  useEffect(() => {
    if (isPlaying) setCircleEditActive(false);
  }, [isPlaying]);

  const togglePlay = useCallback(() => {
    const v = videoRef.current;
    if (!v) return;
    if (v.paused) v.play().catch(() => {}); else v.pause();
  }, []);

  const handleVideoAreaTap = useCallback(() => {
    if (circleEditActive) { setCircleEditActive(false); return; }
    if (!editable) togglePlay();
  }, [circleEditActive, editable, togglePlay]);

  const onHighlightChange = useCallback((h) => setHighlight(h), []);
  const onHighlightComplete = useCallback((h) => setHighlight(h), []);

  return (
    <div style={{ margin: '20px auto', width: '100%', maxWidth: 640, boxSizing: 'border-box', padding: '0 8px' }}>
      <div style={{ marginBottom: 12, display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap' }}>
        <button
          data-testid="toggle-player-boxes"
          onClick={() => setShowPlayerBoxes((v) => !v)}
          style={{ padding: '8px 12px', background: '#374151', color: '#fff', borderRadius: 6 }}
        >
          {showPlayerBoxes ? 'Tracking: ON' : 'Tracking: OFF'}
        </button>
        <button
          data-testid="play-pause"
          onClick={togglePlay}
          style={{ padding: '8px 12px', background: '#7c3aed', color: '#fff', borderRadius: 6 }}
        >
          Play / Pause
        </button>
        <span data-testid="status" style={{ color: '#d1d5db', fontSize: 12 }}>
          {`editable=${editable} circleEdit=${circleEditActive} overrideUsed=${overrideUsed} playing=${isPlaying} t=${currentTime.toFixed(2)}`}
        </span>
      </div>

      {/* Video container. Tap-nav mirrors OverlayModeView: YIELDS while editable, and a
          plain tap OUTSIDE the circle exits circle-edit. */}
      <div
        className="video-container"
        data-testid="video-container"
        style={{ position: 'relative', width: '100%', maxWidth: 640, aspectRatio: '640 / 360', background: '#000' }}
        onClick={handleVideoAreaTap}
      >
        <video
          ref={videoRef}
          src="/overlaydiag-sample.mp4"
          muted
          playsInline
          preload="auto"
          style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }}
        />
        <HighlightOverlay
          videoRef={videoRef}
          videoMetadata={VIDEO_METADATA}
          currentHighlight={highlight}
          onHighlightChange={onHighlightChange}
          onHighlightComplete={onHighlightComplete}
          isEnabled
          zoom={ZOOM}
          panOffset={PAN_OFFSET}
          editable={editable}
          onCircleTap={showPlayerBoxes ? handleCircleTap : undefined}
        />
        <OverrideHint visible={showOverrideHint} text={overrideHintText} />
      </div>
    </div>
  );
}

createRoot(document.getElementById('overlaydiag-t5610-root')).render(<OverrideDiagHarness />);
