import { useRef, useState, useCallback } from 'react';
import { createRoot } from 'react-dom/client';
import { VideoPlayer } from '../components/VideoPlayer';
import HighlightOverlay from '../modes/overlay/overlays/HighlightOverlay';
import '../index.css'; // Tailwind — .video-container / stage box classes need it

/**
 * T5676 — DEV-ONLY real-browser harness for the aspect-aware Overlay video stage.
 *
 * The live QA account (imankh@gmail.com) may not always have an exported reel in
 * BOTH aspects (9:16 AND 16:9) reachable in Overlay, so this harness mounts the REAL
 * VideoPlayer(fitToAspect) + REAL HighlightOverlay for one sample of each aspect,
 * side by side, inside OverlayModeView's EXACT stage box (stageBoxClass/stageBoxStyle
 * mirrored verbatim from modes/OverlayModeView.jsx `useAspectStage` branch) so the
 * Playwright spec can assert "no pillarbox + ellipse aligned" without depending on
 * account data. jsdom is insufficient (T5390/T5570 lesson: layout/hit-testing needs a
 * real browser).
 *
 * Sample videos are ffmpeg-generated by the Playwright spec's beforeAll to /tmp and
 * served via page.route from disk (vite's publicDir listing is cached at server
 * startup — files added after boot 404, per T5590 lesson). aspectdiag.html is not a
 * vite build input, so this never enters the production bundle.
 */

const STAGES = [
  {
    testId: 'stage-wrap-portrait-9x16',
    label: '9:16 portrait',
    src: '/aspectdiag-9x16.mp4',
    metadata: { width: 1080, height: 1920 },
  },
  {
    testId: 'stage-wrap-landscape-16x9',
    label: '16:9 landscape',
    src: '/aspectdiag-16x9.mp4',
    metadata: { width: 1920, height: 1080 },
  },
];

const ZOOM = 1;
const PAN_OFFSET = { x: 0, y: 0 };
const NOOP_HANDLERS = {};

function initialHighlight(metadata) {
  // Centered ellipse sized relative to the frame — mirrors a plausible spotlight.
  return {
    x: metadata.width / 2,
    y: metadata.height / 2,
    radiusX: metadata.width * 0.12,
    radiusY: metadata.height * 0.18,
    strokeOpacity: 0.85,
    fillOpacity: 0.05,
    color: '#FFD400',
  };
}

function AspectStage({ testId, label, src, metadata }) {
  const videoRef = useRef(null);
  const [highlight, setHighlight] = useState(() => initialHighlight(metadata));
  // Mirrors OverlayModeView's `isFullscreen`/`mobileFs` VIEW STATE only. The real
  // browser Fullscreen API is deliberately NOT invoked here: it's orthogonal to
  // what this harness proves (ellipse alignment holds when `isFullscreen`/
  // `mobileFs` flip the CSS branch) and calling `requestFullscreen()` in this
  // headless sandbox (no compositor/X server) closed the browser context
  // outright. The real app's actual Fullscreen API wiring (`useFullscreenControls`)
  // is separately proven working via the real-account test in this same spec
  // (its fullscreen button is the real hook, not this harness).
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [mobileFs, setMobileFs] = useState(false);

  const onHighlightChange = useCallback((h) => setHighlight(h), []);
  const onHighlightComplete = useCallback((h) => setHighlight(h), []);

  const toggleFullscreen = useCallback(() => setIsFullscreen((v) => !v), []);
  const toggleMobileFs = useCallback(() => setMobileFs((v) => !v), []);

  // Mirrors modes/OverlayModeView.jsx useAspectStage branch verbatim (T5676):
  // aspect-fit stage ONLY when NOT fullscreen/mobileFs; both those modes fall back
  // to w-full/h-full (unchanged pre-existing behavior — out of scope for T5676).
  const useAspectStage = !isFullscreen && !mobileFs;
  const stageBoxClass = useAspectStage
    ? 'relative bg-gray-900 rounded-lg overflow-hidden mx-auto w-full max-w-full lg:w-fit lg:h-[70vh] lg:max-h-[70vh]'
    : `relative bg-gray-900 ${mobileFs ? 'w-full h-full' : 'flex-1 min-h-0'}`;
  const stageBoxStyle = useAspectStage ? { aspectRatio: `${metadata.width} / ${metadata.height}` } : undefined;

  return (
    <div data-testid={testId} style={{ marginBottom: 24 }}>
      <div style={{ color: '#9ca3af', fontSize: 13, marginBottom: 6, fontFamily: 'sans-serif' }}>{label}</div>
      <div style={{ marginBottom: 8, display: 'flex', gap: 8 }}>
        <button
          data-testid={`${testId}-fullscreen-btn`}
          onClick={toggleFullscreen}
          style={{ padding: '4px 10px', background: '#374151', color: '#fff', borderRadius: 4, fontSize: 12 }}
        >
          {isFullscreen ? 'Exit fullscreen' : 'Enter fullscreen'}
        </button>
        <button
          data-testid={`${testId}-mobilefs-btn`}
          onClick={toggleMobileFs}
          style={{ padding: '4px 10px', background: '#374151', color: '#fff', borderRadius: 4, fontSize: 12 }}
        >
          {mobileFs ? 'Exit mobileFs' : 'Enter mobileFs'}
        </button>
      </div>
      <div className={mobileFs ? 'fixed inset-0 z-50 bg-gray-900' : ''}>
        <div className={stageBoxClass} style={stageBoxStyle}>
          <VideoPlayer
            videoRef={videoRef}
            videoUrl={src}
            handlers={NOOP_HANDLERS}
            fitToAspect={useAspectStage}
            isFullscreen={isFullscreen}
            zoom={ZOOM}
            panOffset={PAN_OFFSET}
            overlays={[
              <HighlightOverlay
                key="highlight"
                videoRef={videoRef}
                videoMetadata={metadata}
                currentHighlight={highlight}
                onHighlightChange={onHighlightChange}
                onHighlightComplete={onHighlightComplete}
                isEnabled
                editable
                isFullscreen={isFullscreen}
                zoom={ZOOM}
                panOffset={PAN_OFFSET}
              />,
            ]}
          />
        </div>
      </div>
    </div>
  );
}

function AspectDiagHarness() {
  return (
    <div style={{ padding: 16, maxWidth: 1280, margin: '0 auto' }}>
      {STAGES.map((s) => (
        <AspectStage key={s.testId} {...s} />
      ))}
    </div>
  );
}

createRoot(document.getElementById('aspectdiag-root')).render(<AspectDiagHarness />);
